<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Xuatbaocao\Module'                        => __DIR__ . '/Module.php',
    'Xuatbaocao\Controller\IndexController' => __DIR__ . '/src/Xuatbaocao/Controller/IndexController.php',
    'XuatbaocaoTest\Framework\TestCase'        => __DIR__ . '/tests/Xuatbaocao/Framework/TestCase.php',
    'XuatbaocaoTest\SampleTest'                => __DIR__ . '/tests/Xuatbaocao/SampleTest.php',
);
