<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class thongtinngungnghi extends \Application\Entity\thongtinngungnghi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'MaTTNgungNghi', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'TuNgay', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'DenNgay', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'LyDo', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'NgayNopDon', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'miengiamthue', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'nguoinopthue');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'MaTTNgungNghi', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'TuNgay', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'DenNgay', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'LyDo', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'NgayNopDon', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'miengiamthue', '' . "\0" . 'Application\\Entity\\thongtinngungnghi' . "\0" . 'nguoinopthue');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (thongtinngungnghi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setMaTTNgungNghi($MaTTNgungNghi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaTTNgungNghi', array($MaTTNgungNghi));

        return parent::setMaTTNgungNghi($MaTTNgungNghi);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaTTNgungNghi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaTTNgungNghi', array());

        return parent::getMaTTNgungNghi();
    }

    /**
     * {@inheritDoc}
     */
    public function getTuNgay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTuNgay', array());

        return parent::getTuNgay();
    }

    /**
     * {@inheritDoc}
     */
    public function getDenNgay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDenNgay', array());

        return parent::getDenNgay();
    }

    /**
     * {@inheritDoc}
     */
    public function getLyDo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLyDo', array());

        return parent::getLyDo();
    }

    /**
     * {@inheritDoc}
     */
    public function getNgayNopDon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNgayNopDon', array());

        return parent::getNgayNopDon();
    }

    /**
     * {@inheritDoc}
     */
    public function getMiengiamthue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiengiamthue', array());

        return parent::getMiengiamthue();
    }

    /**
     * {@inheritDoc}
     */
    public function getNguoinopthue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNguoinopthue', array());

        return parent::getNguoinopthue();
    }

    /**
     * {@inheritDoc}
     */
    public function setIDngungnghi($MaTTNgungNghi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIDngungnghi', array($MaTTNgungNghi));

        return parent::setIDngungnghi($MaTTNgungNghi);
    }

    /**
     * {@inheritDoc}
     */
    public function setTuNgay($TuNgay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTuNgay', array($TuNgay));

        return parent::setTuNgay($TuNgay);
    }

    /**
     * {@inheritDoc}
     */
    public function setDenNgay($DenNgay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDenNgay', array($DenNgay));

        return parent::setDenNgay($DenNgay);
    }

    /**
     * {@inheritDoc}
     */
    public function setLyDo($LyDo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLyDo', array($LyDo));

        return parent::setLyDo($LyDo);
    }

    /**
     * {@inheritDoc}
     */
    public function setNgayNopDon($NgayNopDon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNgayNopDon', array($NgayNopDon));

        return parent::setNgayNopDon($NgayNopDon);
    }

    /**
     * {@inheritDoc}
     */
    public function setMiengiamthue($miengiamthue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiengiamthue', array($miengiamthue));

        return parent::setMiengiamthue($miengiamthue);
    }

    /**
     * {@inheritDoc}
     */
    public function setNguoinopthue($nguoinopthue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNguoinopthue', array($nguoinopthue));

        return parent::setNguoinopthue($nguoinopthue);
    }

}
