<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class coquanthue extends \Application\Entity\coquanthue implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'MaCoQuan', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'TenGoi', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'doithue', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'chicucthue', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'phuongs', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'users');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'MaCoQuan', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'TenGoi', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'doithue', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'chicucthue', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'phuongs', '' . "\0" . 'Application\\Entity\\coquanthue' . "\0" . 'users');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (coquanthue $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMaCoQuan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaCoQuan', array());

        return parent::getMaCoQuan();
    }

    /**
     * {@inheritDoc}
     */
    public function getTenGoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTenGoi', array());

        return parent::getTenGoi();
    }

    /**
     * {@inheritDoc}
     */
    public function getDoithue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoithue', array());

        return parent::getDoithue();
    }

    /**
     * {@inheritDoc}
     */
    public function getChicucthue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChicucthue', array());

        return parent::getChicucthue();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhuongs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhuongs', array());

        return parent::getPhuongs();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', array());

        return parent::getUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaCoQuan($MaCoQuan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaCoQuan', array($MaCoQuan));

        return parent::setMaCoQuan($MaCoQuan);
    }

    /**
     * {@inheritDoc}
     */
    public function setTenGoi($TenGoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTenGoi', array($TenGoi));

        return parent::setTenGoi($TenGoi);
    }

    /**
     * {@inheritDoc}
     */
    public function setDoithue($doithue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoithue', array($doithue));

        return parent::setDoithue($doithue);
    }

    /**
     * {@inheritDoc}
     */
    public function setChicucthue($chicucthue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChicucthue', array($chicucthue));

        return parent::setChicucthue($chicucthue);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhuongs($phuongs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhuongs', array($phuongs));

        return parent::setPhuongs($phuongs);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsers($users)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsers', array($users));

        return parent::setUsers($users);
    }

}
