<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class muclucngansach extends \Application\Entity\muclucngansach implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'TieuMuc', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'TenGoi', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'chitietchungtus', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'kythuemgs', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'sonos', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'thues', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'thuemonbais', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'dukienthues', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'dukientruythus', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'truythus', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'dukienmbs');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'TieuMuc', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'TenGoi', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'chitietchungtus', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'kythuemgs', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'sonos', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'thues', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'thuemonbais', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'dukienthues', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'dukientruythus', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'truythus', '' . "\0" . 'Application\\Entity\\muclucngansach' . "\0" . 'dukienmbs');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (muclucngansach $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTieuMuc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTieuMuc', array());

        return parent::getTieuMuc();
    }

    /**
     * {@inheritDoc}
     */
    public function getTenGoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTenGoi', array());

        return parent::getTenGoi();
    }

    /**
     * {@inheritDoc}
     */
    public function getChitietchungtus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChitietchungtus', array());

        return parent::getChitietchungtus();
    }

    /**
     * {@inheritDoc}
     */
    public function getKythuemgs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKythuemgs', array());

        return parent::getKythuemgs();
    }

    /**
     * {@inheritDoc}
     */
    public function getSonos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSonos', array());

        return parent::getSonos();
    }

    /**
     * {@inheritDoc}
     */
    public function getThues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThues', array());

        return parent::getThues();
    }

    /**
     * {@inheritDoc}
     */
    public function getThuemonbais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThuemonbais', array());

        return parent::getThuemonbais();
    }

    /**
     * {@inheritDoc}
     */
    public function getDukienthues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDukienthues', array());

        return parent::getDukienthues();
    }

    /**
     * {@inheritDoc}
     */
    public function getDukientruythus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDukientruythus', array());

        return parent::getDukientruythus();
    }

    /**
     * {@inheritDoc}
     */
    public function getTruythus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTruythus', array());

        return parent::getTruythus();
    }

    /**
     * {@inheritDoc}
     */
    public function getDukienmbs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDukienmbs', array());

        return parent::getDukienmbs();
    }

    /**
     * {@inheritDoc}
     */
    public function setTieuMuc($TieuMuc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTieuMuc', array($TieuMuc));

        return parent::setTieuMuc($TieuMuc);
    }

    /**
     * {@inheritDoc}
     */
    public function setTenGoi($TenGoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTenGoi', array($TenGoi));

        return parent::setTenGoi($TenGoi);
    }

    /**
     * {@inheritDoc}
     */
    public function setChitietchungtus($chitietchungtus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChitietchungtus', array($chitietchungtus));

        return parent::setChitietchungtus($chitietchungtus);
    }

    /**
     * {@inheritDoc}
     */
    public function setKythuemgs($kythuemgs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKythuemgs', array($kythuemgs));

        return parent::setKythuemgs($kythuemgs);
    }

    /**
     * {@inheritDoc}
     */
    public function setSonos($sonos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSonos', array($sonos));

        return parent::setSonos($sonos);
    }

    /**
     * {@inheritDoc}
     */
    public function setThues($thues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThues', array($thues));

        return parent::setThues($thues);
    }

    /**
     * {@inheritDoc}
     */
    public function setThuemonbais($thuemonbais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThuemonbais', array($thuemonbais));

        return parent::setThuemonbais($thuemonbais);
    }

    /**
     * {@inheritDoc}
     */
    public function setDukienthues($dukienthues)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDukienthues', array($dukienthues));

        return parent::setDukienthues($dukienthues);
    }

    /**
     * {@inheritDoc}
     */
    public function setDukientruythus($dukientruythus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDukientruythus', array($dukientruythus));

        return parent::setDukientruythus($dukientruythus);
    }

    /**
     * {@inheritDoc}
     */
    public function setTruythus($truythus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTruythus', array($truythus));

        return parent::setTruythus($truythus);
    }

    /**
     * {@inheritDoc}
     */
    public function setDukienmbs($dukienmbs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDukienmbs', array($dukienmbs));

        return parent::setDukienmbs($dukienmbs);
    }

}
