<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class thue extends \Application\Entity\thue implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'KyThue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'nguoinopthue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'muclucngansach', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'truythu', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'TenGoi', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'SanLuong', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'GiaTinhThue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'DoanhThuChiuThue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'TiLeTinhThue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'ThueSuat', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'SoTien', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'NgayPhaiNop', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'TrangThai', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'SoChungTu');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'KyThue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'nguoinopthue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'muclucngansach', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'truythu', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'TenGoi', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'SanLuong', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'GiaTinhThue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'DoanhThuChiuThue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'TiLeTinhThue', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'ThueSuat', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'SoTien', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'NgayPhaiNop', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'TrangThai', '' . "\0" . 'Application\\Entity\\thue' . "\0" . 'SoChungTu');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (thue $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTrangThai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrangThai', array());

        return parent::getTrangThai();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrangThai($TrangThai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrangThai', array($TrangThai));

        return parent::setTrangThai($TrangThai);
    }

    /**
     * {@inheritDoc}
     */
    public function getKyThue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKyThue', array());

        return parent::getKyThue();
    }

    /**
     * {@inheritDoc}
     */
    public function getNguoinopthue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNguoinopthue', array());

        return parent::getNguoinopthue();
    }

    /**
     * {@inheritDoc}
     */
    public function getMuclucngansach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMuclucngansach', array());

        return parent::getMuclucngansach();
    }

    /**
     * {@inheritDoc}
     */
    public function getTenGoi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTenGoi', array());

        return parent::getTenGoi();
    }

    /**
     * {@inheritDoc}
     */
    public function getSanLuong()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSanLuong', array());

        return parent::getSanLuong();
    }

    /**
     * {@inheritDoc}
     */
    public function getGiaTinhThue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGiaTinhThue', array());

        return parent::getGiaTinhThue();
    }

    /**
     * {@inheritDoc}
     */
    public function getDoanhThuChiuThue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoanhThuChiuThue', array());

        return parent::getDoanhThuChiuThue();
    }

    /**
     * {@inheritDoc}
     */
    public function getTiLeTinhThue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiLeTinhThue', array());

        return parent::getTiLeTinhThue();
    }

    /**
     * {@inheritDoc}
     */
    public function getThueSuat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThueSuat', array());

        return parent::getThueSuat();
    }

    /**
     * {@inheritDoc}
     */
    public function getSoTien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoTien', array());

        return parent::getSoTien();
    }

    /**
     * {@inheritDoc}
     */
    public function getNgayPhaiNop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNgayPhaiNop', array());

        return parent::getNgayPhaiNop();
    }

    /**
     * {@inheritDoc}
     */
    public function getKetSo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKetSo', array());

        return parent::getKetSo();
    }

    /**
     * {@inheritDoc}
     */
    public function setKyThue($KyThue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKyThue', array($KyThue));

        return parent::setKyThue($KyThue);
    }

    /**
     * {@inheritDoc}
     */
    public function setNguoinopthue($nguoinopthue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNguoinopthue', array($nguoinopthue));

        return parent::setNguoinopthue($nguoinopthue);
    }

    /**
     * {@inheritDoc}
     */
    public function setMuclucngansach($muclucngansach)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMuclucngansach', array($muclucngansach));

        return parent::setMuclucngansach($muclucngansach);
    }

    /**
     * {@inheritDoc}
     */
    public function setTenGoi($TenGoi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTenGoi', array($TenGoi));

        return parent::setTenGoi($TenGoi);
    }

    /**
     * {@inheritDoc}
     */
    public function setSanLuong($SanLuong)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSanLuong', array($SanLuong));

        return parent::setSanLuong($SanLuong);
    }

    /**
     * {@inheritDoc}
     */
    public function setGiaTinhThue($GiaTinhThue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGiaTinhThue', array($GiaTinhThue));

        return parent::setGiaTinhThue($GiaTinhThue);
    }

    /**
     * {@inheritDoc}
     */
    public function setDoanhThuChiuThue($DoanhThuChiuThue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoanhThuChiuThue', array($DoanhThuChiuThue));

        return parent::setDoanhThuChiuThue($DoanhThuChiuThue);
    }

    /**
     * {@inheritDoc}
     */
    public function setTiLeTinhThue($TiLeTinhThue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiLeTinhThue', array($TiLeTinhThue));

        return parent::setTiLeTinhThue($TiLeTinhThue);
    }

    /**
     * {@inheritDoc}
     */
    public function setThueSuat($ThueSuat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThueSuat', array($ThueSuat));

        return parent::setThueSuat($ThueSuat);
    }

    /**
     * {@inheritDoc}
     */
    public function setSoTien($SoTien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSoTien', array($SoTien));

        return parent::setSoTien($SoTien);
    }

    /**
     * {@inheritDoc}
     */
    public function setNgayPhaiNop($NgayPhaiNop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNgayPhaiNop', array($NgayPhaiNop));

        return parent::setNgayPhaiNop($NgayPhaiNop);
    }

    /**
     * {@inheritDoc}
     */
    public function setKetSo($KetSo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKetSo', array($KetSo));

        return parent::setKetSo($KetSo);
    }

}
