<?php
use Zend\Form\Form;
use Application\Entity\user;
/* @var $user user */
$user = $this->identity();
$this->headscript()->appendFile($this->basePath() . '/public/' . 'js/jquery.validate.min.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'js/additional-methods.min.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlycanbothue/Canbothue/form-validation-script.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlycanbothue/Canbothue/index_Canbothue.js');
/* @var $form Form */
 /* @var $dsCanBoThue user */
$form = $this->formCanBoThue;
?>



<div class="container-fluid">




	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN THEME CUSTOMIZER-->
			<!-- END THEME CUSTOMIZER-->
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">QUẢN LÝ CÁN BỘ THUẾ</h3>
			<ul class="breadcrumb">
				<li class="active">
                     <a href="<?php echo $this->url('quanlycanbothue/default',array('controller'=>'Canbothue','action'=>'index'));?>">Danh sách cán bộ thuế</a>             
                </li>
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>

	<!-- BEGIN EDITABLE TABLE widget-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE widget-->

			<div class="widget red">

				<div class="widget-title">
					<h4>Danh sách cán bộ thuế</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<div class="clearfix">
							<div class="btn-group">

								<button id="editable-sample_new"
									class="btn green">
									Thêm mới <i class="icon-plus"></i>
								</button>
							</div>
							
								<div class="btn-group pull-right">
							
							     <div class="control-group">
                                    
                                    <div class="controls">
                                    </div>
                                </div>
							</div>
						</div>
	
						
						<div class="space12"></div>
					<table cellspacing="0" class="table table-striped table-bordered"
						width="100%" id="editable-sample">
						<thead>
							<tr>
									<th>Mã cán bộ thuế (*)</th>
						            <th>Tên cán bộ thuế (*)</th>
									<th>Chức vụ (*)</th>
									<th>Email (*)</th>
									<th>Cơ quan trực thuộc (*)</th>
									<th>Trạng thái (*)</th>

    								<th>Sửa</th>
							</tr>
						</thead>
						<tbody id="chitiet">
										
										
										<?php if($dsCanBoThue!=null):?>
										
        										
                                       <?php foreach ($dsCanBoThue as $cbt):?>
                                       
                            <tr class="odd">
                            
								
								<td><?php echo $cbt->getMaUser()?></td>
								<td><?php echo $cbt->getTenUser()?></td>
								<td>
								<?php 
								    switch ($cbt->getLoaiUser()) {
								        case 1:
								            echo 'ADMIN';
								            break;
								        case 2:
								            echo 'Chi Cục Trưởng';
								            break;
								        case 3:
							                echo 'Đội Trưởng';
							                break;
						                case 4:
						                    echo 'Cán Bộ Viên';
						                    break; 
								    }
								?>
								</td>
								<td><?php echo $cbt->getEmail()?></td>
								<td><?php echo $cbt->getCoquanthue()->getTenGoi()?></td>
								<td>
								<?php 

								    switch ($cbt->getTrangThai()) {
								        //dang hoạt động
								        case 1:
								            echo '<button class="btn btn-success"><i class="icon-ok"></i></button>';
								            break;
								        //tạm ngừng
								        case 0:
								            echo '<button class="btn btn-warning"><i class="icon-pause"></i></button>';
								            break;
								        
								    }
								?>
								
								</td>
								
									
								<td><a class="edit" href="">Sửa</a></td>
					            
							</tr>
                                
                                <?php endforeach;?>
										<?php endif;?>		
  
							</tbody>
					</table>
						
						
					</div>
				</div>
			</div>
			<!-- END EXAMPLE TABLE widget-->
		</div>
	</div>


	<!-- END PAGE -->
</div>
<!-- END CONTAINER -->

<div id="DialogFormCBT" style="width: 800px; margin-left: -400px;"
            	class="modal hide fade" tabindex="-1" role="dialog"
            	aria-labelledby="myModalLabel1" aria-hidden="false"
            	style="display: block;">
            	<div class="modal-header">
            		<button type="button" class="close" data-dismiss="modal"
            			aria-hidden="true">×</button>
            		<h3>Thêm Cán Bộ Thuế</h3>
            	</div>
            	
            <!-- BEGIN FORM-->
              <form id="signupForm" action="post" class="form-horizontal cmxform">
            	<div class="modal-body"> 		
                            <?php echo $this->formelement($form->get('HanhDong'))?>
                            
                            <!-- Chi nhap so, nho hon 65 ky tu -->
                            <div class="control-group">
                                <label for="MaUser" class="control-label">Mã User</label>
                                <div class="controls">
                                    <?php echo $this->formelement($form->get('MaUser'))?>
                                    <span class="help-inline MaUser" style="display: none;"></span>
                                </div> 
                            </div>
                            
                            <div class="control-group">
                                <label class="control-label">Loại User</label>
                                <div class="controls">
                                    <input type="text" class="span4" value="<?php if($user->getLoaiUser()==3){ echo "Cán Bộ Viên";}?>" disabled="disabled"/>
                                </div>
                            </div>
                            
                            <!-- nho hon 256 ky tu -->
                            <div class="control-group">
                                <label for="TenUser" class="control-label">Tên User</label>
                                <div class="controls">
                                    <?php echo $this->formelement($form->get('TenUser'))?>
                                </div>
                            </div>                           
                            
                           <div class="control-group ">
                                <label for="Email" class="control-label">Email</label>
                                <div class="controls">
                                    <?php echo $this->formelement($form->get('Email'))?>
                                    <span class="help-inline Email" style="display: none;"></span>
                                </div>
                           </div>
                            
                            <div class="control-group ">
                                    <label for="MatKhau" class="control-label">Password</label>
                                    <div class="controls">
                                        <?php echo $this->formelement($form->get('MatKhau'))?>
                                        
                                    </div>
                                </div>
                            <div class="control-group ">
                                    <label for="confirm_password" class="control-label">Confirm Password</label>
                                    <div class="controls">
                                        <input class="span6 " id="confirm_password" name="confirm_password" type="password" />
                                    </div>
                                </div>
                            
                            <div class="control-group">
                                <label class="control-label">Trạng Thái</label>
                                <div class="controls">
                                    <div id="text-toggle-button">
                                        <input name="TrangThai" type="checkbox" checked="checked">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="control-label">Cơ Quan Thuế</label> 
                                <div class="controls">
                                    <input type="text" class="span4" value="<?php echo $user->getCoquanthue()->getTenGoi();?>" disabled="disabled"/>
                                </div>
                            </div>

                           
            		
            		
            		

                 
                 

        </div>
        <div class="modal-footer">
		 <button type="submit" class="btn btn-success">Submit</button>
         <button type="button" class="btn cancel">Cancel</button>
        </div>
        </form>
</div>

