<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Quanlyuser\Module'                        => __DIR__ . '/Module.php',
    'Quanlyuser\Controller\IndexController' => __DIR__ . '/src/Quanlyuser/Controller/IndexController.php',
    'QuanlyuserTest\Framework\TestCase'        => __DIR__ . '/tests/Quanlyuser/Framework/TestCase.php',
    'QuanlyuserTest\SampleTest'                => __DIR__ . '/tests/Quanlyuser/SampleTest.php',
);
