<?php

$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Xuatbaocao/Index/index_Xuatbaocao.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/jquery.fileDownload.js');



?>

<div class="space12"></div>
<div class="row-fluid">
                    <div class="span12" >
                        <!-- BEGIN BASIC PORTLET-->
                        <div class="widget green">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i> Danh sách biểu mẫu theo quy trình quản lý hộ kinh doanh </h4>
                            <span class="tools">
                                <a href="javascript:;" class="icon-chevron-down"></a>
                                
                            </span>
                            </div>
                            <div class="widget-body">
                                <table class="table table-striped table-bordered table-advance table-hover HKD">
                                    <thead>
                                    <tr>
                                        <th><i class="icon-bullhorn"></i> STT</th>
                                        <th class="hidden-phone"><i class="icon-question-sign"></i> Tên biểu mẫu</th>
                                        <th><i class="icon-bookmark"></i> Mẫu số</th>
                                        <th><i class=" icon-edit"></i> Kỳ thuế</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                     <tr>
                                        <td>1</td>
                                        <td class="hidden-phone">Danh bạ quản lý hộ kinh doanh</td>
                                        <td>01/QTr-HKD</td>
                                                <td> 
                                                                                                 							
                            							
                    								<div class="input-append date Years" style="margin-top: 10px"
                    									data-date="102/2012" data-date-format=" yyyy"
                    									data-date-viewmode="years" data-date-minviewmode="years">
                    									
                    								<input readonly="readonly" style="width: 50px" type="text">
                                                     
                                                     
                                                    
                    								 <span class="add-on"> <i class="icon-calendar"> </i></span>
                    								 
                    								 <img class="loading" style="margin-left:10px;display:none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                                        
                    								 
                    									
                    								</div>
                    								
                    								
                                                
                                                
                                                </td>
                                        <td>
                                            <button class="btn btn-success xuatcaobao"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                     
                                    
                                     <tr>
                                        <td>2</td>
                                        <td class="hidden-phone">Danh sách hộ kinh doanh nghỉ, bỏ kinh doanh</td>
                                        <td>04/QTr-HKD</td>
                                                <td> 
                                                                                                 							
                            							
                    								<div class="input-append date months"
									data-date="102/2012" data-date-format="mm/yyyy"
									data-date-viewmode="years" data-date-minviewmode="months">
									
								<input readonly="readonly" style="width: 50px" type="text" >
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                    								 
                    									
                    								</div>
                    								
                                                
                                                
                                                </td>
                                        <td>
                                           <button class="btn btn-success xuatcaobao"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                    
                                     <tr>
                                        <td>3</td>
                                        <td class="hidden-phone">Danh sách hộ kinh doanh thuộc diện không phải nộp thuế GTGT, thuế TNCN</td>
                                        <td>10/QTr-HKD</td>
                                                <td> 
                                                                                                 							
                            							
                    								
                    								<div class="input-append date months"
									data-date="102/2012" data-date-format="mm/yyyy"
									data-date-viewmode="years" data-date-minviewmode="months">
									
								<input readonly="readonly" style="width: 50px" type="text" >
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                    								 
                    									
                    								</div>
                    								
                    								
                                                
                                                
                                                </td>
                                        <td>
                                             <button class="btn btn-success xuatcaobao"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                    
                                     <tr>
                                        <td>4</td>
                                        <td class="hidden-phone">Danh sách hộ kinh doanh tạm nghỉ kinh doanh được miễn, giảm thuế</td>
                                        <td>12/QTr-HKD</td>
                                                <td> 
                                                           							
                            							
                    								<div class="input-append date months"
									data-date="102/2012" data-date-format="mm/yyyy"
									data-date-viewmode="years" data-date-minviewmode="months">
									
								<input readonly="readonly" style="width: 50px" type="text" >
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                    								 
                    									
                    								</div>
                    								
                    								 
                    									
                    								</div>
                    								
                    								
                                                
                                                
                                                </td>
                                        <td>
                                            <button class="btn btn-success xuatcaobao"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                     <tr>
                                        <td>6</td>
                                        <td class="hidden-phone">Danh sách hộ kinh doanh và mức thuế phải nộp</td>
                                        <td>11/QTr-HKD</td>
                                                <td> 
                                                                                                 							
                            							
                    								<div class="input-append date" id="Years_01/QTr-HKD" style="margin-top: 10px"
                    									data-date="102/2012" data-date-format=" yyyy"
                    									data-date-viewmode="years" data-date-minviewmode="years">
                    									
                    								<input readonly="readonly" class="m-ctrl-medium" type="text">
                                                     
                                                     
                                                    
                    								 <span class="add-on"> <i class="icon-calendar"> </i></span>
                    								 
                    								 <img class="loading" style="margin-left:10px;display:none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                                        
                    								 
                    									
                    								</div>
                    								
                    								
                                                
                                                
                                                </td>
                                        <td>
                                            <button class="btn btn-success"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                     
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- END BASIC PORTLET-->
                    </div>
                </div>
                
                
                <div class="row-fluid">
                    <div class="span12" >
                        <!-- BEGIN BASIC PORTLET-->
                        <div class="widget green">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i> Danh sách biểu mẫu sổ bộ thuế </h4>
                            <span class="tools">
                                <a href="javascript:;" class="icon-chevron-down"></a>
                                
                            </span>
                            </div>
                            <div class="widget-body">
                                <table class="table table-striped table-bordered table-advance table-hover HKD">
                                    <thead>
                                    <tr>
                                        <th><i class="icon-bullhorn"></i> STT</th>
                                        <th class="hidden-phone"><i class="icon-question-sign"></i> Tên biểu mẫu</th>
                                        <th><i class="icon-bookmark"></i> Mẫu số</th>
                                        <th><i class=" icon-edit"></i> Kỳ thuế</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                     <tr>
                                        <td>1</td>
                                        <td class="hidden-phone">Sổ bộ thuế môn bài</td>
                                        <td>01/SB-HKD</td>
                                                <td> 
                                                                                                 							
                            							
                    								<div class="input-append date Years" style="margin-top: 10px"
                    									data-date="102/2012" data-date-format=" yyyy"
                    									data-date-viewmode="years" data-date-minviewmode="years">
                    									
                    								<input readonly="readonly" style="width: 50px" type="text">
                                                     
                                                     
                                                    
                    								 <span class="add-on"> <i class="icon-calendar"> </i></span>
                    								 
                    								 <img class="loading" style="margin-left:10px;display:none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                                        
                    								 
                    									
                    								</div>
                    								
                    								
                                                
                                                
                                                </td>
                                        <td>
                                            <button class="btn btn-success xuatcaobao"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                     
                                    
                                     <tr>
                                        <td>2</td>
                                        <td class="hidden-phone">SỔ BỘ THUẾ HỘ KINH DOANH NỘP THUẾ THEO PHƯƠNG PHÁP	KHOÁN<br> THUỘC DIỆN KHÔNG PHẢI NỘP THUẾ GTGT & THUẾ TNCN		
                                        </td>
                                        <td>03a/SB-HKD</td>
                                                <td> 
                                                                                                 							
                            							
                    								<div class="input-append date months"
									data-date="102/2012" data-date-format="mm/yyyy"
									data-date-viewmode="years" data-date-minviewmode="months">
									
								<input readonly="readonly" style="width: 50px" type="text" >
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                    								 
                    									
                    								</div>
                    								
                                                
                                                
                                                </td>
                                        <td>
                                           <button class="btn btn-success xuatcaobao"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                    
                                     <tr>
                                        <td>3</td>
                                        <td class="hidden-phone">Danh sách hộ kinh doanh thuộc diện không phải nộp thuế GTGT, thuế TNCN</td>
                                        <td>10/QTr-HKD</td>
                                                <td> 
                                                                                                 							
                            							
                    								
                    								<div class="input-append date months"
									data-date="102/2012" data-date-format="mm/yyyy"
									data-date-viewmode="years" data-date-minviewmode="months">
									
								<input readonly="readonly" style="width: 50px" type="text" >
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                    								 
                    									
                    								</div>
                    								
                    								
                                                
                                                
                                                </td>
                                        <td>
                                             <button class="btn btn-success xuatcaobao"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                    
                                     <tr>
                                        <td>4</td>
                                        <td class="hidden-phone">Danh sách hộ kinh doanh tạm nghỉ kinh doanh được miễn, giảm thuế</td>
                                        <td>12/QTr-HKD</td>
                                                <td> 
                                                           							
                            							
                    								<div class="input-append date months"
									data-date="102/2012" data-date-format="mm/yyyy"
									data-date-viewmode="years" data-date-minviewmode="months">
									
								<input readonly="readonly" style="width: 50px" type="text" >
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                    								 
                    									
                    								</div>
                    								
                    								 
                    									
                    								</div>
                    								
                    								
                                                
                                                
                                                </td>
                                        <td>
                                            <button class="btn btn-success xuatcaobao"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                     <tr>
                                        <td>6</td>
                                        <td class="hidden-phone">Danh sách hộ kinh doanh và mức thuế phải nộp</td>
                                        <td>11/QTr-HKD</td>
                                                <td> 
                                                                                                 							
                            							
                    								<div class="input-append date" id="Years_01/QTr-HKD" style="margin-top: 10px"
                    									data-date="102/2012" data-date-format=" yyyy"
                    									data-date-viewmode="years" data-date-minviewmode="years">
                    									
                    								<input readonly="readonly" class="m-ctrl-medium" type="text">
                                                     
                                                     
                                                    
                    								 <span class="add-on"> <i class="icon-calendar"> </i></span>
                    								 
                    								 <img class="loading" style="margin-left:10px;display:none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
                                        
                    								 
                    									
                    								</div>
                    								
                    								
                                                
                                                
                                                </td>
                                        <td>
                                            <button class="btn btn-success"><i class="icon-book"></i></button>      
                                        </td>
                                    </tr>
                                    
                                     
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- END BASIC PORTLET-->
                    </div>
                </div>
                
                