<?php
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlynguoinopthue/thongtinngungnghi/index_thongtinngungnghi.js');

// daterangepicker
$this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap-daterangepicker/moment.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap-daterangepicker/daterangepicker.js');
$this->headLink()->appendStylesheet($this->basePath() . '/public/' . 'assets/bootstrap-daterangepicker/daterangepicker-bs2.css');

?>


<div class="container-fluid">




	<div class="row-fluid">
		<div class="span12">

			<h3 class="page-title">QUẢN LÝ THÔNG TIN NGƯNG NGHĨ CỦA NGƯỜI NỘP
				THUẾ</h3>
			<ul class="breadcrumb">

				<li class="active">Quản lý thông tin ngưng nghĩ</li>


			</ul>

		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">

			<div class="widget purple">

				<div class="widget-title">
					<h4>Danh sách thông tin ngưng nghĩ xem theo từng hộ kinh doanh</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a>
					</span>
				</div>
				<div class="widget-body">
				
				<div class="row-fluid">
				
				<div class="span3 bio" >

					<div class="space30">
					<a class="icon-btn span2 TimNNT" style="margin-right: 10px" href="#">
                            <i class="icon-search"></i>
                            <div>Tìm</div>
                        </a></div>
					               
                     <h2><span class="MaSoThue">...</span></h2>
                     <p>Tên : <span class="TenHKD">...</span></p>
                     <p><label>Số CMND </label>: <span class="SoCMND">...</span></p>
                     <p><label>Số GPKD </label>: <span class="SoGPKD">...</span></p>
                     <p><label>Địa Chỉ CT </label>: <span class="DiaChiCT">...</span></p>
                     <p><label>Thời Điểm KD </label>: <span class="ThoiDiemBDKD">...</span></p>
                     <p><label>Ngày cấp MST </label>: <span class="NgayCapMST">...</span></p>
                     <p><label>Nghề kinh doanh </label>: <span class="NgheKD">...</span></p>
                     <hr>
                                 
					
					
					
					</div>
                        

					<div class="span9">
						<div class="clearfix">
							<div class="btn-group">


								<button id="editable-sample_new" class="btn btn-success">
									Thêm mới <i class="icon-plus"></i>
								</button>
<!-- <button style="margin-left: 5px;" id="xoa_nhieu"
									class="btn btn-edit">
									Xóa đã chọn <i class="icon-remove"></i>
								</button> -->
								
                                <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">

							</div>

						</div>
						<div class="space12"></div>
						<table cellspacing="0" class="table table-striped table-bordered" MaSoThue=""
							width="100%" id="editable-sample">
							<thead>
								<tr>
									<th>MaTTNgungNghi</th>
									<th>Từ ngày (*)</th>
									<th>Đến ngày (*)</th>
									<th>Lý do (*)</th>
									<th>Ngày nộp đơn (*)</th>
									<th>Sửa</th>
									<th>Xóa</th>
								</tr>
							</thead>
							<tbody>


							</tbody>
						</table>
					</div>
				
				
				
				</div>
				
					



				</div>
			</div>
		</div>
	</div>
</div>