<?php

use Application\Entity\chungtu;
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Chambo/index_Chambo.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/jquery.fileDownload.js');
/* @var $ChungTus chungtu */
$ChungTus = $this->chungtus;
?>



<div class="container-fluid">

	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN THEME CUSTOMIZER-->
			<!-- END THEME CUSTOMIZER-->
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">QUẢN LÝ CHỨNG TỪ</h3>
			<ul class="breadcrumb">
			
				 
                       
                       <li class="active">
				 <a href="<?php echo $this->url('quanlysothue/default',array('controller'=>'Chungtu','action'=>'index'));?>">Danh sách chứng từ</a>

				<span class="divider">/</span>
				</li>
				<li class="active">Chấm bộ thuế</li>
                      
				
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>

	<!-- BEGIN EDITABLE TABLE widget-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE widget-->

			<div class="widget purple">

				<div class="widget-title">
					<h4>Danh sách chứng từ</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a>
					</span>
				</div>
				<div class="widget-body">
				
				<div class="clearfix">
				           
						<form action="#" class="form-horizontal">
							<div class="control-group">
							<label class="control-label">Kỳ thuế: </label>
							<div class="controls">
								<div class="input-append date dpMonths" 
									data-date="102/2012" data-date-format="mm/yyyy"
									data-date-viewmode="years" data-date-minviewmode="months">
									
								<input readonly="readonly" class="m-ctrl-medium" type="text">
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
								</div>
								<div id="progess_dpmonths" style="width: 247px; display: none;" class="progress progress-striped progress-danger active">
                                     <div style="width: 100%;" class="bar"></div>
                                </div>
								<p class="help-block"></p>
							</div>
						      </div>
						</form>
						
						<div class="clearfix">
						  <button 
									class="btn btn-link ChonChungTu">
									  Chọn tất cả
									<i class="icon-search"></i>
							     </button>
						
							<div class="btn-group">
                                
								
								<button 
									class="btn btn-danger ChamBo">
									Chấm bộ <i class="icon-bitcoin"></i>
								</button>
							
                                
                                
							</div>

							<div class="btn-group pull-right">
							
							     
							
								<!-- <button class="btn dropdown-toggle" data-toggle="dropdown">
									Tùy chọn <i class="icon-angle-down"></i>
								</button>
								<ul class="dropdown-menu pull-right">
									<li><a href="#">Print</a></li>
									<li><a href="#">Save as PDF</a></li>
									<li><a href="#">Export to Excel</a></li>
								</ul> -->
							</div>
						</div>
						

				</div>
				    

					<div class="space12"></div>
					
					
						
						
						
						
						

						
						      <table cellspacing="0" class="table table-striped table-bordered"
						width="100%" id="editable-chambo">
						<thead>
							<tr>
								    
									<th>Số chứng từ (*)</th>
						            <th>Ngày chứng từ</th>
						            <th>Ngày hạch toán</th>
									<th>Mã số thuế</th>
									<th>Tên HKD</th>
									<th>Kỳ thuế</th>
    								
    								<th>Số tiền</th>
    								<th>Tiểu muc</th>					
							</tr>
    						</thead>
            				        <tbody>
            				            <?php foreach ($ChungTus as $ChungTu):?>
            				                    <?php $ChiTietChungTus = $ChungTu->getChitietchungtus();?>
            				                    <?php foreach ($ChiTietChungTus as $ChiTietChungTu):?>
            				                            <tr class="odd">
                            
                            								
                            								<td><input class="check_item" type="checkbox">
                            								<span class="SoChuongTu"><?php echo $ChungTu->getSoChungTu();?></span>
                            								</td>
                            								
                            								<td><?php echo $ChungTu->getNgayChungTu()->format('d-m-Y')?></td>
                            								<td><?php echo $ChiTietChungTu->getNgayHachToan()->format('d-m-Y')?></td>
                            								<td><?php echo $ChungTu->getNguoinopthue()->getMaSoThue()?></td>
                            								<td><?php echo $ChungTu->getNguoinopthue()->getTenHKD()?></td>
                            								<td><?php echo $ChiTietChungTu->getKyThue()?></td>
                            								
                            								<td><?php echo $ChiTietChungTu->getMuclucngansach()->getTieuMuc()?></td>
                            								<td><?php echo $ChiTietChungTu->getSoTien()?></td>
                            						
                            							</tr>          
            				                    
            				                    <?php endforeach;?>
            				            
            				            
            				            <?php endforeach;?>
            				        
            				        
        							</tbody>
    					    </table>
						
						
						
						
					
				
					
				        
				
				
					
				</div>
			</div>
			<!-- END EXAMPLE TABLE widget-->
		</div>
	</div>


	<!-- END PAGE -->
</div>
<!-- END CONTAINER -->