<?php
use Application\Entity\dukienmb;
use Quanlysothue\Froms\UploadForm;
use Application\Entity\thuemonbai;
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Thuemonbai/index_Thuemonbai.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/jquery.fileDownload.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap/js/bootstrap-fileupload.js');
$this->headLink()->appendStylesheet($this->basePath() . '/public/' . 'assets/bootstrap/css/bootstrap-fileupload.css');

 /* @var $dsThueMonBai thuemonbai */
/* @var $formUp UploadForm */
$formUp = $this->formUp;

use Application\Entity\user;
/* @var $user user */
$user = $this->identity();

?>



<div class="container-fluid">




	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN THEME CUSTOMIZER-->
			<!-- END THEME CUSTOMIZER-->
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">QUẢN LÝ THUẾ MÔN BÀI</h3>
			<ul class="breadcrumb">
				<li class="active">
                     <a href="<?php echo $this->url('quanlysothue/default',array('controller'=>'Thuemonbai','action'=>'index'));?>">Danh sách thuế môn bài</a>             
                </li>
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>
<input type="hidden" id="LoaiUser" name="LoaiUser" value=<?php echo $user->getLoaiUser()?>>
	<!-- BEGIN EDITABLE TABLE widget-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE widget-->

			<div class="widget red">

				<div class="widget-title">
					<h4>Danh sách thuế môn bàin bài</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<form action="#" class="form-horizontal">
							<div class="control-group">
							<label class="control-label">Năm: </label>
							<div class="controls">
								<div class="input-append date" id="dpThueMonBai"
									data-date="102/2012" data-date-format=" yyyy"
									data-date-viewmode="years" data-date-minviewmode="years">
									
								<input readonly="readonly" class="m-ctrl-medium" type="text" name="KyThue"  id="kythue" >
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
								</div>
								<div id="progess_dpmonths" style="width: 247px; display: none;" class="progress progress-striped progress-danger active">
                                     <div style="width: 100%;" class="bar"></div>
                                </div>
								<p class="help-block"></p>
							</div>
						</div>
						</form>
						<div class="clearfix">
							<div class="btn-group">

								<?php if($user->getLoaiUser()==3):?>
								<button 
									class="btn btn-link ChonChoDuyet">
									  Chọn "Chờ duyệt" 
									<i class="icon-search"></i>
							     </button>
								
								
								<button  style="margin-left: 5px;" 
									class="btn btn-success Duyet">
									  Duyệt
									<i class="icon-adjust"></i>
							     </button>
								<?php endif;?>
								
								
							     
							     <button  style="margin-left: 5px;"
									class="btn btn-success GhiSo">
									   Ghi sổ
									<i class="icon-adjust"></i>
							     </button>
								
								     
                                
							</div>

							
						</div>
						
	   <span class="MaCB" style="display: none;"><?php echo $user->getMaUser()?></span>
						
						<div class="space12"></div>
					<table cellspacing="0" class="table table-striped table-bordered"
						width="100%" id="TableThueMonBai">
						<thead>
							<tr>
								    <th><input id="check_all" type="checkbox"></th>
									<th>Mã số thuế (*)</th>
						            <th>Tên HKD</th>
						            <th>Tiểu Mục(*)</th>
									<th>Bậc môn bài</th>
									<th>Doanh số (*)</th>
									<th>Ngày phải nộp (*)</th>
									<th>Số tiền (*)</th>
									<th>Trạng thái </th>
									
									
    								<th>Sửa</th>
    								<th>Xóa</th>
							</tr>
						</thead>
						<tbody id="chitiet">
										
										
										<?php if($dsThueMonBai!=null):?>
										
        										
                                       <?php foreach ($dsThueMonBai as $thue):?>
                                       
                            <tr class="odd">
                            
								<td><input class="check_item" type="checkbox"></td>
								
								<td><?php echo $thue->getNguoinopthue()->getMaSoThue()?></td>
								<td><?php echo $thue->getNguoinopthue()->getTenHKD()?></td>
								<td><?php echo $thue->getMuclucngansach()->getTieuMuc()?></td>
								<td><?php echo mb_substr($thue->getMuclucngansach()->getTenGoi(),13,17,'UTF-8');?></td>
								<td><?php echo $thue->getDoanhSo()?></td>
								<td><?php echo $thue->getNgayPhaiNop()?></td>
								<td><?php echo $thue->getSoTien()?></td>
								<td>
    								<?php if($thue->getTrangThai()==0):?>	
    								<span style="color:red;">Chờ duyệt</span>
    								<?php else:?>
    								<span style="color:green;">Đã duyệt</span>
    								<?php endif;?>
            					</td>
							    
							    
							    <?php if($thue->getTrangThai()==0):?>	
								<?php echo $user->getLoaiUser()==3?'<td><a class="edit" href="">Edit</a></td>':'<td></td>'?>
								<?php echo $user->getLoaiUser()==3?'<td><a class="Delete" href="">Delete</a></td>':'<td></td>'?>
								<?php else:?>
								<td></td>
								<td></td>
								<?php endif;?>
							</tr>                
                                <?php endforeach;?>
        										          	
										<?php endif;?>		
  
							</tbody>
					</table>
						
						
					</div>
				</div>
			</div>
			<!-- END EXAMPLE TABLE widget-->
		</div>
	</div>


	<!-- END PAGE -->
</div>
<!-- END CONTAINER -->


<div id="DialogGhiSo" style="width: 800px; margin-left: -400px;"
            	class="modal hide fade" tabindex="-1" role="dialog"
            	aria-labelledby="myModalLabel1" aria-hidden="false"
            	style="display: block;">
            	<div class="modal-header">
            		<button type="button" class="close" data-dismiss="modal"
            			aria-hidden="true">×</button>
            		<h3>Dialog ghi sổ</h3>
            	</div>
            	
            <!-- BEGIN FORM-->
              
        <div class="modal-body"> 		
                            
            		<div>
					 
                <img class="loading_GhiSo" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">

            		</div>
            		
            		<table cellspacing="0" class="table table-striped table-bordered" width="100%" id="TableGhiSo" style="margin-left: 0px; width: 740px;">
						<thead>
							<tr>
								    <th><input id="check_all_ghiso" type="checkbox"></th>
									<th>Mã số thuế</th>
						            <th>Tên HKD</th>
									<th>Tiểu Mục (*)</th>
									<th>Bậc môn bài</th>
									<th>Doanh số (*)</th>
									<th>Ngày phải nộp</th>
									<th>Số tiền (*)</th>
									<th>Mã CB</th>

							</tr>
						</thead>
						<tbody>
                        </tbody>
					</table>
            		
            		
            		

                 
                 

        </div>
        <div class="modal-footer">
		 <button type="button" id="GhiSo"  class="btn btn-success">Ghi sổ</button>
         <button type="button" class="btn cancel">Cancel</button>
        </div>
       
</div>
