<?php 
use Application\Entity\user;
/* @var $user user */
?>
<div class="container-fluid">	
	
	<div class="row-fluid">
		<div class="span12">
            <!-- BEGIN PAGE TITLE & BREADCRUMB-->
            <h3 class="page-title">
             Thông tin cá nhân
            </h3>
            <ul class="breadcrumb">
               <li>
                   <a href="#">Quản lý cán bộ thuế</a>
                   <span class="divider">/</span>
               </li>
               <li class="active">
                   Thông tin cá nhân
               </li>
               <li class="pull-right search-wrap">
               </li>
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
      </div>
	</div>
	<div class="row-fluid">
                    <div class="span8">
                        <!-- BEGIN GRID SAMPLE PORTLET-->
                        <div class="widget green">
                            <div class="widget-title">
                                <h4><i class="icon-user"></i> </h4>
                                        <span class="tools">
                                        <a class="icon-chevron-down" href="javascript:;"></a>
                                        <a class="icon-remove" href="javascript:;"></a>
                                        </span>
                            </div>
                            <div class="widget-body" style="height: 400px">
                                
                                
                                <div class="span12 biomy">
                                     <h2 class="text-info"><?php echo $user->getTenUser();?></h2>
                                     <p><label>Mã cán bộ thuế </label>: <?php echo $user->getMaUser();?></p>
                                     <p><label>Tên cán bộ thuế </label>: <?php echo $user->getTenUser();?></p>
                                     <p><label>Chức vụ </label>:
                                    <?php 
    								    switch ($user->getLoaiUser()) {
    								        case 1:
    								            echo 'ADMIN';
    								            break;
    								        case 2:
    								            echo 'Chi Cục Trưởng';
    								            break;
    								        case 3:
    							                echo 'Đội Trưởng';
    							                break;
    						                case 4:
    						                    echo 'Cán Bộ Viên';
    						                    break; 
    								    }
								    ?>
                                     </p>
                                     
                                     
                                     <p><label>Email </label>: <a href="#"><?php echo $user->getEmail()?></a></p>
                                     <p><label>Mã cán bộ quản lý </label>:  <?php echo $user->getParentUser()->getMaUser();?></p>
                                     <p><label>Tên cán bộ quản lý </label>:  <?php echo $user->getParentUser()->getTenUser();?></p>
                                     <p><label>Cơ quan trực thuộc </label>: <?php echo $user->getCoquanthue()->getTenGoi()?></p>
                                 
                                 <div class="space10"></div>
                                 <hr>
                                 <div class="space10"></div>

                                 <div class="text-center">
                                     <a href="<?php echo $this->url('quanlycanbothue/default',array('controller'=>'Thongtincanhan','action'=>'doimatkhau'));?>"><button class="btn btn-danger ">Đổi mật khẩu</button></a>
                                     <a href="<?php echo $this->url('quanlyuser',array('controller'=>'Login','action'=>'logout'));?>"><button class="btn ">Đăng xuất</button></a>
                                 </div>

                             </div>                             
                            </div>
                        </div>
                        <!-- END GRID PORTLET-->
                    </div>
	   </div>
 	</div>
                             