<!-- BEGIN PAGE TITLE & BREADCRUMB-->
<h3 class="page-title">
 Grids
</h3>
<ul class="breadcrumb">
   <li>
       <a href="#">Home</a>
       <span class="divider">/</span>
   </li>
   <li>
       <a href="#">Components</a>
       <span class="divider">/</span>
   </li>
   <li class="active">
       Grids
   </li>
   <li class="pull-right search-wrap">
       <form action="search_result.html" class="hidden-phone">
           <div class="input-append search-input-area">
               <input class="" id="appendedInputButton" type="text">
               <button class="btn" type="button"><i class="icon-search"></i> </button>
           </div>
       </form>
   </li>
</ul>
<!-- END PAGE TITLE & BREADCRUMB-->


                             <div class="span8 bio">
                                 <h2>About Smith</h2>
                                 <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Donec ut volutpat metus. Aliquam tortor lorem, fringilla tempor dignissim at, pretium et arcu. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.</p>
                                 <div class="space15"></div>
                                 <h2>Bio Graph</h2>
                                 <p><label>First Name </label>: Jonathan</p>
                                 <p><label>Last Name </label>: Smith</p>
                                 <p><label>Country </label>: Australia</p>
                                 <p><label>Bithday </label>: 13 July 1983</p>
                                 <p><label>Occupation </label>: Designer</p>
                                 <p><label>Email </label>: <a href="#">smith@vectorlab.net</a></p>
                                 <p><label>Phone </label>: (12) 03 4567890</p>
                                 <p><label>Website Url </label>: <a href="#">http://www.demowebsite.com</a></p>
                                 <div class="space15"></div>
                                 <hr>
                                 <div class="space15"></div>

                                 <h2>Project Progress</h2>
                                 <ul class="unstyled">
                                     <li>
                                           Envato Website <strong class="label"> 48%</strong>
                                         <div class="space10"></div>
                                         <div class="progress">
                                             <div class="bar" style="width: 48%;"></div>
                                         </div>
                                     </li>
                                     <li>
                                         Themeforest CMS Dashboard <strong class="label label-success"> 85%</strong>
                                         <div class="space10"></div>
                                         <div class="progress progress-success">
                                             <div class="bar" style="width: 85%;"></div>
                                         </div>
                                     </li>
                                     <li>
                                         VectorLab Portfolio <strong class="label label-important"> 65%</strong>
                                         <div class="space10"></div>
                                         <div class="progress progress-danger">
                                             <div class="bar" style="width: 65%;"></div>
                                         </div>
                                     </li>

                                 </ul>
                                 <div class="text-center">
                                     <button class="btn btn-primary ">All Projects</button>
                                 </div>
                                 <div class="space20"></div>

                             </div>