<?php 
use Application\Entity\user;
/* @var $user user */
?>
<div class="container-fluid">	
	
	<div class="row-fluid">
		<div class="span12">
            <!-- BEGIN PAGE TITLE & BREADCRUMB-->
            <h3 class="page-title">
             Thông tin cá nhân
            </h3>
            <ul class="breadcrumb">
               <li>
                   <a href="#">Quản lý cán bộ thuế</a>
                   <span class="divider">/</span>
               </li>
               <li class="active">
                   Thông tin cá nhân
               </li>
               <li class="pull-right search-wrap">
               </li>
            </ul>
            <!-- END PAGE TITLE & BREADCRUMB-->
      </div>
	</div>
	<div class="row-fluid">
                    <div class="span8">
                        <!-- BEGIN GRID SAMPLE PORTLET-->
                        <div class="widget green">
                            <div class="widget-title">
                                <h4><i class="icon-reorder"></i> </h4>
                                        <span class="tools">
                                        <a class="icon-chevron-down" href="javascript:;"></a>
                                        <a class="icon-remove" href="javascript:;"></a>
                                        </span>
                            </div>
                            <div class="widget-body" style="height: 400px">
                                
                                
                                <div class="span12 biomy">
                                     <h2 class="text-info"><?php echo $user->getTenUser();?></h2>
                                     <p><label>Mã cán bộ thuế </label>: Jonathan</p>
                                     <p><label>Tên cán bộ thuế </label>: Smith</p>
                                     <p><label>Chức vụ </label>: Australia</p>
                                     <p><label>Email </label>: <a href="#">smith@vectorlab.net</a></p>
                                     <p><label>Mã cán bộ quản lý </label>:  03 4567890</p>
                                     <p><label>Tên cán bộ quản lý </label>:  Trần Văn A</p>
                                     <p><label>Cơ quan trực thuộc </label>: Đội thuế LXP 4</p>
                                 
                                 <div class="space10"></div>
                                 <hr>
                                 <div class="space10"></div>

                                 <div class="text-center">
                                     <a href="<?php echo $this->url('quanlycanbothue/default',array('controller'=>'Thongtincanhan','action'=>'doimatkhau'));?>"><button class="btn btn-danger ">Đổi mật khẩu</button></a>
                                     <a href="<?php echo $this->url('quanlyuser',array('controller'=>'Login','action'=>'logout'));?>"><button class="btn ">Đăng xuất</button></a>
                                 </div>

                             </div>                             
                            </div>
                        </div>
                        <!-- END GRID PORTLET-->
                    </div>
	   </div>
 	</div>
                             