
<?php 
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlynguoinopthue/Nguoinopthue/persit_NguoiNopThue.js');

?>
<?php use Zend\Form\Form;
use Application\Entity\user;
/* @var $form Form */

/* @var $user user */
$user = $this->identity();
?>

<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN THEME CUSTOMIZER-->
			<!-- END THEME CUSTOMIZER-->
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">THÊM NGƯỜI NỘP THUẾ</h3>
			<ul class="breadcrumb">
				 <li>
                       <a href="<?php echo $this->url('quanlynguoinopthue/default',array('controller'=>'nguoinopthue','action'=>'index'));?>">Danh sách người nộp thuế</a>
                       <span class="divider">/</span>
                       </li>
				<li class="active">Thêm người nộp thuế</li>
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>
	
	
	
	<div class="row-fluid">
                <div class="span12">
                    <!-- BEGIN SAMPLE FORMPORTLET-->
                    <div class="widget green">
                        <div class="widget-title">
                            <h4><i class="icon-reorder"></i> Thêm Người Nộp Thuế </h4>
                            <span class="tools">
                            <a href="javascript:;" class="icon-chevron-down"></a>
                            <a href="javascript:;" class="icon-remove"></a>
                            </span>
                        </div>
                        <div class="widget-body">
                            <!-- BEGIN FORM-->
                            <form action="<?php echo $this->url('quanlynguoinopthue/default',array('controller'=>'nguoinopthue','action'=>'persit')); ?>" class="form-horizontal">
                            
                            <!-- Chi nhap so, Lon hon 9 ky tu, nho hon 21 ky tu -->
                            <div class="control-group">
                                <label class="control-label">Mã Số Thuế (*)</label>
                                <div class="controls input-icon">
                                    <?php echo $this->formelement($form->get('MaSoThue'))?>
                                    <span  style="display: none"  class="input-success tooltips check_">
                                         <i class="icon-exclamation-sign"></i>
                                   </span>
                                   
                                    <div id="progress_masothue" style="width: 498px;display: none;" class="progress progress-striped progress-success active">
                                            <div style="width: 100%;" class="bar"></div>
                                    </div>
                                    
                            
                                    <span class="help-inline"><?php echo $this->formelementerrors($form->get('MaSoThue'))?></span>
                                </div>
                            </div>
                            
                                                        
                            <div class="control-group">
                                    <label class="control-label">Ngày cấp MST (*)</label>
                                    <div class="controls">
                                        <?php echo $this->formelement($form->get('NgayCapMST'))?>
                                        
                                        <span class="help-inline"><?php echo $this->formelementerrors($form->get('NgayCapMST'))?></span>
                                    </div>
                            </div>
                            
                            <!-- nho hon 129 ky tu -->
                            <div class="control-group">
                                <label class="control-label">Tên Hộ Kinh Doanh (*)</label>
                                <div class="controls">
                                   <?php echo $this->formelement($form->get('TenHKD'))?>
                                    <span class="help-inline"><?php echo $this->formelementerrors($form->get('TenHKD'))?></span>
                                </div>
                            </div>
                            
                            <!-- Chi nhap so, Lon hon 9 ky tu, nho hon 21 ky tu -->
                            <div class="control-group">
                                <label class="control-label">Số CMND (*)</label>
                                <div class="controls">
                                    <?php echo $this->formelement($form->get('SoCMND'))?>
                                    <span class="help-inline"><?php echo $this->formelementerrors($form->get('SoCMND'))?></span>
                            	</div>
                            </div>
                            
                            <!-- nho hon 256 ky tu -->
                            <div class="control-group">
                                <label class="control-label">Địa chỉ cư trú (*)</label>
                                <div class="controls">
                                    <?php echo $this->formelement($form->get('DiaChiCT'))?>
                                    <span class="help-inline"><?php echo $this->formelementerrors($form->get('DiaChiCT'))?></span>
                                </div>
                            </div>
                            
                            <!-- nho hon 256 ky tu -->
                            <div class="control-group">
                                <label class="control-label">Địa chỉ kinh doanh (*)</label>
                                <div class="controls">
                                    <?php echo $this->formelement($form->get('DiaChiKD'))?>,
                                    <?php echo $this->formelement($form->get('Phuong'))?>,
                                    <?php echo $this->formelement($form->get('Quan'))?>,&nbsp;TP. Hồ Chí Minh
                                </div>
                            </div>
                            <div class="control-group">
                                <div class="controls">
                                    <?php echo $this->formelement($form->get('ChanLe'))?>,
                                    <?php echo $this->formelement($form->get('Hem'))?>,
                                    <?php echo $this->formelement($form->get('SoNha'))?>,
                                     <?php echo $this->formelement($form->get('SoNhaPhu'))?>,
                                      <?php echo $this->formelement($form->get('TenDuong'))?>
                                </div>
                            </div>
                            
                            <!-- Chi nhap so, Lon hon 9 ky tu, nho hon 21 ky tu -->
                            <div class="control-group">
                                <label class="control-label">Số GPKD (*)</label>
                                <div class="controls">
                                    <?php echo $this->formelement($form->get('SoGPKD'))?>
                                    <span class="help-inline"><?php echo $this->formelementerrors($form->get('SoGPKD'))?></span>
                            	</div>
                            </div>
                            

                            
                            <div class="control-group">
                                    <label class="control-label">Thời điểm BDKD (*)</label>
                                    <div class="controls">
                                        <?php echo $this->formelement($form->get('ThoiDiemBDKD'))?>
                                        <span class="help-inline"><?php echo $this->formelementerrors($form->get('ThoiDiemBDKD'))?></span>
                                    </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="control-label">Ngành (*)</label>
                                <div class="controls">
                                     <?php echo $this->formelement($form->get('Nganh'))?>
                                        <span class="help-inline"><?php echo $this->formelementerrors($form->get('Nganh'))?></span>
                                </div>
                            </div>
                            
                            <!-- nho hon 256 ky tu -->
                            <div class="control-group">
                                <label class="control-label">Nghề (*)</label>
                                <div class="controls">
                                    
                                    <?php echo $this->formelement($form->get('Nghe'))?>
                                    <span class="help-inline"><?php echo $this->formelementerrors($form->get('Nghe'))?></span>
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="control-label">Cán Bộ Quản Lý</label>
                                <div class="controls">
                                <?php $form->get('CanBoQuanLy')->setAttribute('value', $user->getTenUser())?>
                                    <?php echo $this->formelement($form->get('CanBoQuanLy'))?>
                                    <span class="help-inline"></span>
                                </div>
                            </div>
                            
                            <div class="control-group">
                                <label class="control-label">Đội Thuế</label>
                                <div class="controls">
                                    <?php $form->get('DoiThue')->setAttribute('value', $user->getCoquanthue()->getTenGoi())?>
                                    <?php echo $this->formelement($form->get('DoiThue'))?>
                                    <span class="help-inline"></span>
                                </div>
                            </div>

                            <?php echo $this->formelement($form->get('HanhDong'))?>
                            <div class="form-actions">
                                <?php echo $this->formelement($form->get('Submit'))?>
                                <button type="button" class="btn">Cancel</button>
                            </div>
                            </form>
                            <!-- END FORM-->
                        </div>
                    </div>
                    <!-- END SAMPLE FORM PORTLET-->
                </div>
            </div>