<?php
use Quanlysothue\Froms\UploadForm;
use Application\Entity\truythu;
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Thuetruythu/index_Thuetruythu.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/jquery.fileDownload.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap/js/bootstrap-fileupload.js');
$this->headLink()->appendStylesheet($this->basePath() . '/public/' . 'assets/bootstrap/css/bootstrap-fileupload.css');

 /* @var $dsThueTruyThu truythu */
/* @var $formUp UploadForm */
$formUp = $this->formUp;

use Application\Entity\user;
/* @var $user user */
$user = $this->identity();

?>



<div class="container-fluid">




	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN THEME CUSTOMIZER-->
			<!-- END THEME CUSTOMIZER-->
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">QUẢN LÝ THUẾ TRUY THU</h3>
			<ul class="breadcrumb">
				<li class="active">
                     <a href="<?php echo $this->url('quanlysothue/default',array('controller'=>'Thuetruythu','action'=>'index'));?>">Danh sách truy thu</a>             
                </li>
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>
<input type="hidden" id="LoaiUser" name="LoaiUser" value=<?php echo $user->getLoaiUser()?>>
	<!-- BEGIN EDITABLE TABLE widget-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE widget-->

			<div class="widget red">

				<div class="widget-title">
					<h4>Danh sách thuế truy thu</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<form action="#" class="form-horizontal">
							<div class="control-group">
							<label class="control-label">Kỳ thuế: </label>
							<div class="controls">
								<div class="input-append date" id="dpThueTruyThu"
									data-date="102/2012" data-date-format="mm/yyyy"
									data-date-viewmode="years" data-date-minviewmode="months">
									
								<input readonly="readonly" class="m-ctrl-medium" type="text" name="KyThue"  id="kythue" >
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
								</div>
								<div id="progess_dpmonths" style="width: 247px; display: none;" class="progress progress-striped progress-danger active">
                                     <div style="width: 100%;" class="bar"></div>
                                </div>
								<p class="help-block"></p>
							</div>
						      </div>
						</form>
						<div class="clearfix">
							<div class="btn-group">

								<?php if($user->getLoaiUser()==3):?>
								<button 
									class="btn btn-link ChonChoDuyet">
									  Chọn "Chờ duyệt" 
									<i class="icon-search"></i>
							     </button>
								
								
								<button  style="margin-left: 5px;" 
									class="btn btn-success Duyet">
									  Duyệt
									<i class="icon-adjust"></i>
							     </button>
								<?php endif;?>
								
								
							     
							     <button  style="margin-left: 5px;"
									class="btn btn-success GhiSo">
									   Ghi sổ
									<i class="icon-adjust"></i>
							     </button>
								
								     
                                
							</div>

							
						</div>
						
	   <span class="MaCB" style="display: none;"><?php echo $user->getMaUser()?></span>
						
						<div class="space12"></div>
					<table cellspacing="0" class="table table-striped table-bordered"
						width="100%" id="TableThueTruyThu">
						<thead>
							<tr>
								    <th><input id="check_all" type="checkbox"></th>
									<th>Mã số thuế (*)</th>
						            <th>Tên HKD</th>
									<th>Tiểu Mục (*)</th>
									<th>Doanh thu<br>chịu thuế (*)</th>
									<th>Tỉ lệ<br>tính thuế (*)</th>
									<th>Số tiền (*)</th>
									<th>Lý Do</th>
									<th>Trang thái</th>
									
									
    								<th>Sửa</th>
    								<th>Xóa</th>
							</tr>
						</thead>
						<tbody>
										
										
										<?php if($dsThueTruyThu!=null):?>
										
        										
                                       <?php foreach ($dsThueTruyThu as $thue):?>
                                       
                            <tr class="odd">
                            
								<td><input class="check_item" type="checkbox"></td>
								
								<td><?php echo $thue['thue']['nguoinopthue']['MaSoThue']?></td>
								<td><?php echo $thue['thue']['nguoinopthue']['TenHKD']?></td>
								<td><?php echo $thue['thue']['muclucngansach']['TieuMuc']?></td>
								<td><?php echo $thue['DoanhSo']?></td>
								<td><?php echo $thue['TiLeTinhThue']?></td>
								
								<td><?php echo $thue['SoTien']?></td>
								<td><?php echo $thue['LyDo']?></td>
								<td>
    								<?php if($thue['TrangThai']==0):?>	
    								<span style="color:red;">Chờ duyệt</span>
    								<?php else:?>
    								<span style="color:green;">Đã duyệt</span>
    								<?php endif;?>
            					</td>
							    
							    
							    <?php if($thue['TrangThai']==0):?>	
								<?php echo $user->getLoaiUser()==3?'<td><a class="edit" href="">Edit</a></td>':'<td></td>'?>
								<?php echo $user->getLoaiUser()==3?'<td><a class="Delete" href="">Delete</a></td>':'<td></td>'?>
								<?php else:?>
								<td></td>
								<td></td>
								<?php endif;?>
							</tr>                
                                <?php endforeach;?>
        										          	
										<?php endif;?>		
  
							</tbody>
					</table>
						
						
					</div>
				</div>
			</div>
			<!-- END EXAMPLE TABLE widget-->
		</div>
	</div>


	<!-- END PAGE -->
</div>
<!-- END CONTAINER -->


<div id="DialogGhiSo" style="width: 800px; margin-left: -400px;"
            	class="modal hide fade" tabindex="-1" role="dialog"
            	aria-labelledby="myModalLabel1" aria-hidden="false"
            	style="display: block;">
            	<div class="modal-header">
            		<button type="button" class="close" data-dismiss="modal"
            			aria-hidden="true">×</button>
            		<h3>Dialog ghi sổ</h3>
            	</div>
            	
            <!-- BEGIN FORM-->
              
        <div class="modal-body"> 		
                            
            		<div>
					 
                <img class="loading_GhiSo" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">

            		</div>
            		
            		<table cellspacing="0" class="table table-striped table-bordered" width="100%" id="TableGhiSo" style="margin-left: 0px; width: 740px;">
						<thead>
							<tr>
								    <th><input id="check_all_ghiso" type="checkbox"></th>
									<th>Mã số thuế</th>
						            <th>Tên HKD</th>
									<th>Tiểu Mục (*)</th>
									<th>Doanh thu chịu thuế</th>
									<th>Tỉ lệ tính thuế</th>
									<th>Số tiền</th>
									<th>Lý do</th>
									<th>Mã CB</th>
							</tr>
						</thead>
						<tbody>
                        </tbody>
					</table>
            		
            		
            		

                 
                 

        </div>
        <div class="modal-footer">
		 <button type="button" id="GhiSo"  class="btn btn-success">Ghi sổ</button>
         <button type="button" class="btn cancel">Cancel</button>
        </div>
       
</div>
