<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Quanlynguoinopthue\Module'                        => __DIR__ . '/Module.php',
    'Quanlynguoinopthue\Controller\IndexController' => __DIR__ . '/src/Quanlynguoinopthue/Controller/IndexController.php',
    'QuanlynguoinopthueTest\Framework\TestCase'        => __DIR__ . '/tests/Quanlynguoinopthue/Framework/TestCase.php',
    'QuanlynguoinopthueTest\SampleTest'                => __DIR__ . '/tests/Quanlynguoinopthue/SampleTest.php',
);
