<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Quanlycanbothue\Module'                        => __DIR__ . '/Module.php',
    'Quanlycanbothue\Controller\IndexController' => __DIR__ . '/src/Quanlycanbothue/Controller/IndexController.php',
    'QuanlycanbothueTest\Framework\TestCase'        => __DIR__ . '/tests/Quanlycanbothue/Framework/TestCase.php',
    'QuanlycanbothueTest\SampleTest'                => __DIR__ . '/tests/Quanlycanbothue/SampleTest.php',
);
