<?php
use Application\Entity\nguoinopthue;
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Xuatbangke/index_Xuatbangke.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/jquery.fileDownload.js');
?>

<?php /* @var $dsnnt nguoinopthue */
?>

<div class="container-fluid">
	




	<div class="row-fsluid">
		<div class="span12">
			<!-- BEGIN THEME CUSTOMIZER-->
			<!-- END THEME CUSTOMIZER-->
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">QUẢN LÝ NGƯỜI NỘP THUẾ</h3>
			<ul class="breadcrumb">
				<!--  <li>
                           <a href="#">Home</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="#">Metro Lab</a>
                           <span class="divider">/</span>
                       </li> -->
				<li class="active">Danh sách người nộp thuế</li>
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>

	<!-- BEGIN EDITABLE TABLE widget-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE widget-->

			<div class="widget orange">

				<div class="widget-title">
					<h4>Danh Sách Người Nộp Thuế</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
					<form action="#" class="form-horizontal">
							<div class="control-group">
							<label class="control-label">Kỳ Thuế: </label>
							<div class="controls">
								<div class="input-append date" id="dpMonths"
									data-date="102/2012" data-date-format="mm/yyyy"
									data-date-viewmode="years" data-date-minviewmode="months">
									
								<input readonly="readonly" class="m-ctrl-medium" type="text" name="KyThue"  id="kythue" >
                                
                                
                                
								 <span class="add-on"> <i class="icon-calendar"> </i></span>
								
								
								 <img class="loading" style="margin-left:10px; display : none;" src="<?php echo $this->basePath() . '/public/' . 'img/ajax-loader.gif'?>">
								</div>
								<div id="progess_dpmonths" style="width: 247px; display: none;" class="progress progress-striped progress-danger active">
                                     <div style="width: 100%;" class="bar"></div>
                                </div>
								<p class="help-block"></p>
								
								
								

							</div>
							
							
							
							
							
							
						</div>
						
						</form>
						
								<div class="clearfix">
							<div class="btn-group">

								<button id="TaoBangKe"
									class="btn green">
									Tạo bảng kê <i class="icon-plus"></i>
								</button>
								

							</div>

							
						
								

							
							
							
							<div class="btn-group pull-right">
								<button class="btn dropdown-toggle" data-toggle="dropdown">
									Tùy chọn <i class="icon-angle-down"></i>
								</button>
								<ul class="dropdown-menu pull-right">
									<li class="TaoChungTu"><a href="#">Tạo chứng từ</a></li>
									
								</ul>
							</div>
							</div>
						
						<div class="space15"></div>
						<table  cellspacing="0" class="table table-striped table-bordered"
							width="100%" id="editable-sample">
							<thead>
								<tr>
									
                                    <th><input id="check_all" type="checkbox"></th>
                                    
									<th>Mã số thuế</th>
									<th>Ngày cấp MST</th>
									<th>Tên HKD</th>
									<th>Số CMND</th>
									<th>Địa chỉ CT</th>
									<th>Địa chỉ KD</th>
									<th>Số GPKD</th>
									<th>Thời điểm BDKD</th>
									<th>Ngành</th>
									<th>Nghề</th>
									<th>Cán Bộ QL</th>
									<th>Trang thái</th>
									
								</tr>
							</thead>
							<tbody id="chitiet">

									
										<?php if($dsnnt !=null):?>
										
        										
                                       <?php foreach ($dsnnt  as $nnt):?>
                                       
                                       <?php if($nnt->getUsernnt()!=null):?>
                                        <tr class="odd">
                            
								<td><input class="check_item" type="checkbox"></td>
								
								<td><?php echo $nnt->getMaSoThue()?></td>
								<td><?php echo $nnt->getNgayCapMST()?></td>
								<td><?php echo $nnt->getTenHKD()?></td>
								<td><?php echo $nnt->getSoCMND();?></td>
								<td><?php echo $nnt->getDiaChiCT();?></td>
								<td><?php echo ($nnt->getThongtinnnt()==null) ? 'Hộ nghĩ kinh doanh':$nnt->getThongtinnnt()->getDiaChiKD()?></td>
								<td><?php echo $nnt->getSoGPKD()?></td>
								<td><?php echo $nnt->getThoiDiemBDKD()?></td>
								
								<td><?php echo $nnt->getNNTNganh()==null?'Hộ nghĩ kinh doanh':$nnt->getNNTNganh()->getNganh()->getTenNganh()?></td>
								
								<td><?php echo $nnt->getNgheKD()?></td>
								<td><?php echo $nnt->getUsernnt()==null?'Hộ nghĩ kinh doanh':$nnt->getUsernnt()->getUser()->getTenUser()?></td>	
								<td>  
								    <?php 

								    switch ($nnt->getTrangThai()) {
								        // nghĩ
								        case 0:
								            echo '<button class="btn btn-danger"><i class="icon-ban-circle"></i></button>';
								            break;
								            //dang hoạt động
								        case 1:
								            echo '<button class="btn btn-success"><i class="icon-ok"></i></button>';
								            break;
								            //tạm ngừng
								        case 2:
								            echo '<button class="btn btn-warning"><i class="icon-pause"></i></button>';
								            break;
								        
								    }
								    ?>
								    
								    
								    
								    
								</td>
								
								
							</tr>
                                       
                                       <?php endif;?>
                                       
                                
                                
                                <?php endforeach;?>
        										          
        										
        										
										
										
										<?php endif;?>	
							
							
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<!-- END EXAMPLE TABLE widget-->
		</div>
	</div>


	<!-- END PAGE -->
</div>
<!-- END CONTAINER -->