<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/public' . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/public/' . 'css/style-default.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'css/style-responsive.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'css/style.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'assets/font-awesome/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'assets/bootstrap/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'assets/bootstrap/css/bootstrap-responsive.min.css')?>

        


    </head>
<body id="backgroud">
	
    <?php echo $this->content;?>
</body>


     <?php
        
        echo $this->headScript()

            ->prependFile($this->basePath() . '/public/' . 'js/jquery-1.8.3.min.js');
        ?>

<script type="text/javascript">
 
        
        

var image = new Image;
var width,height;
var imgWidth=0;
var imgHeight=0;
image.src = $('body').css('background-image').replace(/url\(|\)$/ig, "");
image.setAttribute('class','backgroundHide');
$('body').append(image);
$('img.backgroundHide').hide();
var windowWidth = $(window).width();        
var windowHeight = $(window).height();
$('img.backgroundHide').on('load', function(){
	imgWidth = $('img.backgroundHide').width();
	imgHeight = $('img.backgroundHide').height();
});
var background = $('#backgroud');
var x= 0;
var y = 0;
var diChuyenXuong;
var diChuyenLen;
var flag=0;
var tocdo =150;


var diChuyenLen = setInterval(function(){
	background.css('background-position',x+'px'+' '+y+'px');
	
	if(y<=0 && flag ==1)
	    y++;
	else{
	 flag =0;
	}
},tocdo);


var diChuyenXuong = setInterval(function(){
    background.css('background-position',x+'px'+' '+y+'px');
    
    
    if((-y)+windowHeight <= imgHeight && flag==0)
		y--;
	else{
		flag=1;
	}
},tocdo);


    
        



</script>


</html>
