<?php echo $this->doctype(); ?>
<html lang="en">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false)?>

        <?php
        
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>

        <!-- Le styles -->
        
        <?php
        
        echo $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/public' . '/img/favicon.ico'
        ))
            ->prependStylesheet($this->basePath() . '/public/' . 'css/style-default.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'css/style-responsive.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'css/style.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'assets/font-awesome/css/font-awesome.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'assets/bootstrap/css/bootstrap.min.css')
            ->prependStylesheet($this->basePath() . '/public/' . 'assets/bootstrap/css/bootstrap-responsive.min.css')?>

        


    </head>
<body>
	
    <?php echo $this->content;?>
</body>

</html>
