<?php

$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Chungtu/oTable_ChungTu.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Chungtu/oTable_CTChungTu.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/jquery.fileDownload.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap-daterangepicker/moment.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap-daterangepicker/daterangepicker.js');

$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/jquery.fileDownload.js');

$this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap/js/bootstrap-fileupload.js');
$this->headLink()->appendStylesheet($this->basePath() . '/public/' . 'assets/bootstrap/css/bootstrap-fileupload.css');


$this->headLink()->appendStylesheet($this->basePath() . '/public/' . 'assets/bootstrap-daterangepicker/daterangepicker-bs2.css');
/* $this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap/js/bootstrap-fileupload.js');
$this->headLink()->appendStylesheet($this->basePath() . '/public/' . 'assets/bootstrap/css/bootstrap-fileupload.css'); */



?>



<div class="container-fluid">

	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN THEME CUSTOMIZER-->
			<!-- END THEME CUSTOMIZER-->
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">QUẢN LÝ CHỨNG TỪ</h3>
			<ul class="breadcrumb">
			
				 <li class="active">
                           <a href="<?php echo $this->url('quanlysothue/default',array('controller'=>'Chungtu','action'=>'index'));?>">Danh sách chứng từ</a>
                           
                       </li>
                      
				
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>

	<!-- BEGIN EDITABLE TABLE widget-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE widget-->

			<div class="widget purple">

				<div class="widget-title">
					<h4>Danh sách chứng từ</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a>
					</span>
				</div>
				<div class="widget-body">
				
				<div class="clearfix">
				           
						<form action="#" class="form-horizontal">
						
						      <div class="control-group">
                                    <label class="control-label">Xem từ ngày đến ngày</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-calendar"></i></span>
                                            <input id="reservation" type="text" class=" m-ctrl-medium">
                                        </div>
                                        
                                        
                                        
                                        <div class="btn-group pull-right">
							
							     <div class="control-group">
                                    
                                    <div class="controls">
                                        <div data-provides="fileupload" class="fileupload fileupload-new">
                                            <div class="input-append">
                                                <div class="uneditable-input">
                                                    <i class="icon-file fileupload-exists"></i>
                                                    <span class="fileupload-preview"></span>
                                                </div>
                                               <span class="btn btn-file">
                                               <span class="fileupload-new">Select file</span>
                                               <span class="fileupload-exists">Change</span>
                                               <?php echo $this->formelement($formUp->get("file-excel"))?>
                                               </span>
                                                <button style="margin-left: 5px;"  id="Import"
                            						class="btn btn-file">
                            						Import <i class="icon-file"></i>
								                    </button>
								                    <button style="margin-left: 20px" class="btn dropdown-toggle" data-toggle="dropdown">
									Tùy chọn <i class="icon-angle-down"></i>
								</button>
								<ul style="margin-top: -27px" class="dropdown-menu pull-right">
									<li><a href="<?php echo $this->url('quanlysothue/default',array('controller'=>'Chambo','action'=>'index'))?>">Chấm bộ</a></li>
								</ul>
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
							
								
							</div>
                                        
                                        
                                    </div>
                                    
                                    
                                    
                                    
                                    
                                </div>
						
						</form>
						
						
					           
				            
				
				
				</div>
				    
				    
					
					
					
					
					
					
					<div class="row-fluid" >
					
					<div class="span6" style="border: 1px solid #9D4A9C; padding: 10px">
						
						<div class="clearfix">
							<div class="btn-group">
                                
								
								<button  id="editable-chungtu_new"
									class="btn btn-success">
									Thêm mới chứng từ <i class="icon-plus"></i>
								</button>
							
                                
                                
							</div>

							<div class="btn-group pull-right">
							
							     
							
								<!-- <button class="btn dropdown-toggle" data-toggle="dropdown">
									Tùy chọn <i class="icon-angle-down"></i>
								</button>
								<ul class="dropdown-menu pull-right">
									<li><a href="#">Print</a></li>
									<li><a href="#">Save as PDF</a></li>
									<li><a href="#">Export to Excel</a></li>
								</ul> -->
							</div>
						</div>
						
						
						<div class="space12"></div>
	
						

						
						      <table cellspacing="0" class="table table-striped table-bordered"
						width="100%" id="editable-chungtu">
						<thead>
							<tr>
								    <th></th>
									<th>Số chứng từ (*)</th>
						            <th>Ngày chứng từ</th>
								
									<th>Mã số thuế</th>
									<th>Tên HKD</th>
    								<th>Sửa</th>
    								<th>Xóa</th>
							</tr>
    						</thead>
            				        <tbody id="tablechungtu">
        							</tbody>
    					    </table>
						</div>
						
						
						<div class="span6" style="border: 1px solid #9D4A9C; padding: 10px">
						<div style="display: none;" class="progressSoChungTu progress progress-striped progress-success active">
                                <div style="width: 100%; " class="bar" ></div>
                            </div>
						<div class="profile-side-box red">
                                     <h1 class="SoChungTu">Vui lòng chọn số chứng từ</h1>
                                 </div> 
						<div class="clearfix">
							<div class="btn-group">
                                
								
								<button  id="editable-chitietchungtu_new"
									class="btn btn-success">
									Thêm chi tiết chứng từ <i class="icon-plus"></i>
								</button>
								
								<button style="margin-left: 5px;"  id="xoa_nhieu"
									class="btn btn-edit">
									Xóa đã chọn <i class="icon-remove"></i>
								</button>
                                
                               
							</div>
							
							

							<div class="">
							
							    
							
								
							</div>
						</div>
	
						<div class="space12"></div>
						
						
						      <table cellspacing="0" class="table table-striped table-bordered"
						width="100%" id="editable-chitietchungtu">
						<thead>
							<tr>
								    
									<th>Kỳ thuế (*)</th>
						            <th>Tiểu mục (*)</th>
									<th>Ngày hạch toán</th>
									<th>Số tiền</th>
    								<th>Sửa</th>
    								<th>Xóa</th>
							</tr>
    						</thead>
            				        <tbody >
        							</tbody>
    					    </table>
						</div>
					
					</div>
					
					
				        
				
				
					
				</div>
			</div>
			<!-- END EXAMPLE TABLE widget-->
		</div>
	</div>


	<!-- END PAGE -->
</div>
<!-- END CONTAINER -->