<?php

$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Chungtu/oTable_Chungtu.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Chungtu/oTable_CTChungtu.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/jquery.fileDownload.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap-daterangepicker/moment.js');
$this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap-daterangepicker/daterangepicker.js');


$this->headLink()->appendStylesheet($this->basePath() . '/public/' . 'assets/bootstrap-daterangepicker/daterangepicker-bs2.css');
/* $this->headscript()->appendFile($this->basePath() . '/public/' . 'assets/bootstrap/js/bootstrap-fileupload.js');
$this->headLink()->appendStylesheet($this->basePath() . '/public/' . 'assets/bootstrap/css/bootstrap-fileupload.css'); */



?>



<div class="container-fluid">

	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN THEME CUSTOMIZER-->
			<!-- END THEME CUSTOMIZER-->
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">QUẢN LÝ CHỨNG TỪ</h3>
			<ul class="breadcrumb">
			
				 <li class="active">
                           <a href="<?php echo $this->url('quanlysothue/default',array('controller'=>'Dukientruythu','action'=>'index'));?>">Danh sách dự kiến truy thu theo kỳ thuế</a>
                           
                       </li>
                      
				
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>

	<!-- BEGIN EDITABLE TABLE widget-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE widget-->

			<div class="widget purple">

				<div class="widget-title">
					<h4>Danh sách chứng từ</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a>
					</span>
				</div>
				<div class="widget-body">
				
				
				    
				    <div>
						<form action="#" class="form-horizontal">
						
						      <div class="control-group">
                                    <label class="control-label">Xem từ ngày đến ngày</label>
                                    <div class="controls">
                                        <div class="input-prepend">
                                            <span class="add-on"><i class="icon-calendar"></i></span>
                                            <input id="reservation" type="text" class=" m-ctrl-medium">
                                        </div>
                                    </div>
                                </div>
						
						</form>
						
						
					</div>
					
					
					
					
					
					
					<div class="row-fluid" >
					
					<div class="span6" style="border: 1px solid #9D4A9C;">
						
						<div class="clearfix">
							<div class="btn-group">
                                
								
								<button  id="editable-chungtu_new"
									class="btn btn-success">
									Thêm mới chứng từ <i class="icon-plus"></i>
								</button>
							
                                
                                
							</div>

							<div class="btn-group pull-right">
							
							     
							
								<!-- <button class="btn dropdown-toggle" data-toggle="dropdown">
									Tùy chọn <i class="icon-angle-down"></i>
								</button>
								<ul class="dropdown-menu pull-right">
									<li><a href="#">Print</a></li>
									<li><a href="#">Save as PDF</a></li>
									<li><a href="#">Export to Excel</a></li>
								</ul> -->
							</div>
						</div>
						
						
						<div class="space12"></div>
	
						

						
						      <table cellspacing="0" class="table table-striped table-bordered"
						width="100%" id="editable-chungtu">
						<thead>
							<tr>
								    
									<th>Số chứng từ (*)</th>
						            <th>Ngày chứng từ</th>
									<th>Ngày hạch toán</th>
									<th>Mã số thuế</th>
									<th>Tên HKD</th>
    								<th>Sửa</th>
    								<th>Xóa</th>
							</tr>
    						</thead>
            				        <tbody id="tablechungtu">
        							</tbody>
    					    </table>
						</div>
						
						
						<div class="span6" style="border: 1px solid #9D4A9C;">
						<div style="display: none;" class="progressSoChungTu progress progress-striped progress-danger active">
                                <div style="width: 100%; " class="bar" ></div>
                            </div>
						<div class="profile-side-box red">
                                     <h1 class="SoChungTu">Vui lòng chọn số chứng từ</h1>
                                 </div>
						<div class="clearfix">
							<div class="btn-group">
                                
								
								<button  id="editable-chitietchungtu_new"
									class="btn btn-success">
									Thêm chi tiết chứng từ <i class="icon-plus"></i>
								</button>
								
								<button style="margin-left: 5px;"  id="xoa_nhieu"
									class="btn btn-edit">
									Xóa đã chọn <i class="icon-remove"></i>
								</button>
                                
                               
							</div>
							
							

							<div class="">
							
							    
							
								
							</div>
						</div>
	
						<div class="space12"></div>
						
						
						      <table cellspacing="0" class="table table-striped table-bordered"
						width="100%" id="editable-chitietchungtu">
						<thead>
							<tr>
								    
									<th>Kỳ thuế (*)</th>
						            <th>Tiểu mục</th>
									<th>Số tiền</th>
									
    								<th>Sửa</th>
    								<th>Xóa</th>
							</tr>
    						</thead>
            				        <tbody id="tablechitietchungtu">
        							</tbody>
    					    </table>
						</div>
					
					</div>
					
					
				        
				
				
					
				</div>
			</div>
			<!-- END EXAMPLE TABLE widget-->
		</div>
	</div>


	<!-- END PAGE -->
</div>
<!-- END CONTAINER -->