<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Quanlysothue\Module'                        => __DIR__ . '/Module.php',
    'Quanlysothue\Controller\IndexController' => __DIR__ . '/src/Quanlysothue/Controller/IndexController.php',
    'QuanlysothueTest\Framework\TestCase'        => __DIR__ . '/tests/Quanlysothue/Framework/TestCase.php',
    'QuanlysothueTest\SampleTest'                => __DIR__ . '/tests/Quanlysothue/SampleTest.php',
);
