<!-- BEGIN BODY -->
<body class="error-500">
    <div class="error-wrap">
        <h1>KHÔNG CÓ QUYỀN HẠN !</h1>
        <h2>Bạn không có quyền truy cập vào chức năng này</h2>
        <div class="metro green">
           <span> 0 </span>
        </div>
        <div class="metro yellow">
            <span> 0 </span>
        </div>
        <div class="metro purple">
            <span> 0 </span>
        </div>
        <p>Vui lòng thông báo cho quản trị viên hoặc quay lại trang chủ. <a href="
        <?php echo $this->url('home')?>"> Return Home </a></p>
    </div>
</body>
<!-- END BODY -->