<?php
/* @var $form Quanlyuser\Form\LoginForm */
$formThayDoiDiaChiKDNNT = $this->form;

$formThayDoiDiaChiKDNNT->setAttribute('action', $this->url('quanlyuser', array(
    'controller' => 'Login',
    'action' => 'index'
)));
$formThayDoiDiaChiKDNNT->prepare();

echo $this->form()->openTag($formThayDoiDiaChiKDNNT);
?>

<?php




echo $this->formElementErrors($formThayDoiDiaChiKDNNT->get('remenber'));
?>

<div class="lock-header">
	<!-- BEGIN LOGO -->
	<a class="center" id="logo" href="index.html"> <img class="center"
		alt="logo" src="public/img/logo.png">
	</a>
	<!-- END LOGO -->
</div>
<div class="login-wrap">
	<div class="metro single-size red">
		<div class="locked">
			<i class="icon-lock"></i> <span>Login</span>
		</div>
	</div>
	<div class="metro double-size green">

		<div class="input-append lock-input">
					<?php echo $this->formElement($formThayDoiDiaChiKDNNT->get('MaUser'));?>
					
				</div>
    <?php echo $this->formElementErrors($formThayDoiDiaChiKDNNT->get('MaUser'));?>
	</div>
	<div class="metro double-size yellow">

		<div class="input-append lock-input">
					<?php echo $this->formElement($formThayDoiDiaChiKDNNT->get('MatKhau'));?>
				</div>
				<?php echo $this->formElementErrors($formThayDoiDiaChiKDNNT->get('MatKhau'));?>

	</div>
	<div class="metro single-size terques login">

		<button type="submit" class="btn login-btn">
                    Login
                    <i class=" icon-long-arrow-right"></i>
                </button>

	</div>

	<div class="login-footer">
	
	
		<div class="pull-left">
				<?php echo $this->formElement($formThayDoiDiaChiKDNNT->get('remenber'));?>
				<?php echo $this->formLabel($formThayDoiDiaChiKDNNT->get('remenber'));?>
			</div>
			
			
		<div class="forgot-hint pull-right">
			<a id="forget-password" class="" href="javascript:;">Forgot Password?</a>
		</div>
	</div>
</div>


<?php echo $this->form()->closeTag();?>