<?php
use Application\Entity\ketqua;
use Quanlysothue\Froms\FormDKThue;
use Application\Entity\dukienthue;

/* @var $form FormDKThue */


?>
<?php

$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Dukienthue/indexAction.js');
?>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN NOTIFICATION PORTLET-->
			<div class="widget red">
				<div class="widget-title">
					<h4>
						<i class="icon-bar-chart"></i> Bảng thông báo tiến trình
					</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a> <a href="javascript:;"
						class="icon-remove"></a>
					</span>
				</div>
				<div class="widget-body">
			<?php /* @var $kq ketqua */?>
				<?php if(isset($kq)):?>
				     <?php if($kq->getKq()==true):?>
        				        <div class="alert alert-block alert-success fade in">
						<button data-dismiss="alert" class="close" type="button">×</button>
						<h4 class="alert-heading">Success!</h4>
						<p><?php echo $kq->getMessenger();?>.</p>
					</div>
				<?php else:?>
				<div class="alert alert-block alert-error fade in">
						<button data-dismiss="alert" class="close" type="button">×</button>
						<h4 class="alert-heading">Error!</h4>
						<p><?php echo $kq->getMessenger();?>.</p>
					</div>
				     <?php endif;?>

				<?php endif;?>



			</div>
			</div>
			<!-- END NOTIFICATION PORTLET-->
		</div>
	</div>




	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN THEME CUSTOMIZER-->
			<!-- END THEME CUSTOMIZER-->
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">QUẢN LÝ DỰ KIẾN THUẾ</h3>
			<ul class="breadcrumb">
				<!--  <li>
                           <a href="#">Home</a>
                           <span class="divider">/</span>
                       </li>
                       <li>
                           <a href="#">Metro Lab</a>
                           <span class="divider">/</span>
                       </li> -->
				<li class="active">Home</li>
			</ul>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>

	<!-- BEGIN EDITABLE TABLE widget-->
	<div class="row-fluid">
		<div class="span12">
			<!-- BEGIN EXAMPLE TABLE widget-->

			<div class="widget purple">

				<div class="widget-title">
					<h4>Danh sách dự kiến thuế theo kỳ thuế</h4>
					<span class="tools"> <a href="javascript:;"
						class="icon-chevron-down"></a>
					</span>
				</div>
				<div class="widget-body">
					<div>
						<form action="#" class="form-horizontal">
							<div class="control-group">
								<label class="control-label">Kỳ Thuế: </label>
								<div class="controls">
									<div class="input-append date" id="dpMonths"
										data-date="102/2012" data-date-format="mm-yyyy"
										data-date-viewmode="years" data-date-minviewmode="months">

										<input readonly="readonly" class="m-ctrl-medium" type="text"
											name="KyThue" id="kythue"> <span class="add-on"> <i
											class="icon-calendar"> </i></span>
										<div class="progress progress-striped active"
											id="progress_kythue"
											style="width: 219.5px; margin-bottom: 0px; display: none;">
											<div style="width: 100%;" class="bar"></div>
										</div>
									</div>
									<p class="help-block"></p>
								</div>
							</div>
						</form>
						<div class="clearfix">
							<div class="btn-group">

								<button onclick="RedirectThem()" id="editable-sample_new"
									class="btn green">
									Thêm mới <i class="icon-plus"></i>
								</button>

								<button style="margin-left: 5px;" onclick="XoaSelect()"
									id="editable-sample_new" class="btn green">
									Xóa đã chọn <i class="icon-remove"></i>
								</button>

							</div>

							<!-- <div class="btn-group pull-right">
								<button class="btn dropdown-toggle" data-toggle="dropdown">
									Tùy chọn <i class="icon-angle-down"></i>
								</button>
								<ul class="dropdown-menu pull-right">
									<li><a href="#">Print</a></li>
									<li><a href="#">Save as PDF</a></li>
									<li><a href="#">Export to Excel</a></li>
								</ul>
							</div> -->
						</div>
						<div class="space15"></div>
						<table class="table table-striped table-hover table-bordered"
							id="editable-sample">
							<thead>
								<tr>
									<th style="width: 12.0909091234207px;" class="sorting_disabled"
										role="columnheader" rowspan="1" colspan="1" aria-label=""><input
										id="check_all" type="checkbox" class="group-checkable"></th>
									<th>Tiểu mục</th>
									<th>Mã số thuế</th>
									<th>Họ tên</th>
									<th>Địa chỉ</th>
									<th>Tên gọi</th>
									<th>Sản lượng</th>
									<th>Doanh thu chịu thuế</th>
									<th>Tỉ lệ tính thuế</th>
									<th>Thuế suất</th>
									<th>Số tiền</th>
									<th>Cập nhật</th>
									<th>Xóa</th>
								</tr>
							</thead>
							<tbody id="chitiet">
							<?php /* @var $dkts dukienthue */?>
                                <?php foreach ($dkts as $dkt):?>
                                <tr class="odd">
                                    <td class=" sorting_1"><input class="check_item"
										type="checkbox"></td>
                                    <td><?php echo $dkt->getMuclucngansach()->getTieuMuc();?></td>
                                    <td><?php echo $dkt->getNguoinopthue()->getMaSoThue();?></td>
                                    <td><?php echo $dkt->getNguoinopthue()->getTenHKD();?></td>
                                    <td><?php echo $dkt->getNguoinopthue()->getDiaChiCT();?></td>
                                    <td><?php echo $dkt->getTenGoi();?></td>
                                    <td><?php echo $dkt->getSanLuong();?></td>
                                    <td><?php echo $dkt->getDoanhThuChiuThue();?></td>
                                    <td><?php echo $dkt->getTiLeTinhThue();?></td>
                                    <td><?php echo $dkt->getThueSuat();?></td>
                                    <td><?php echo $dkt->getSoTien();?></td>
                                    <td><button
											onclick="RedirectEdit($(this).parents('tr'))"
											class="btn btn-primary">
											<i class="icon-pencil"></i>
										</button></td>
                                    <td><button onclick="deleterow($(this).parents('tr'))"
											class="btn btn-danger">
											<i class="icon-trash "></i>
										</button></td>
                                
									
									
								</tr>
                                
                                <?php endforeach;?>

							</tbody>
						</table>
					</div>
				</div>
			</div>
			<!-- END EXAMPLE TABLE widget-->
		</div>
	</div>


	<!-- END PAGE -->
</div>
<!-- END CONTAINER -->