<?php
use Application\Entity\ketqua;
use Quanlysothue\Froms\FormDKThue;
/* @var $form FormDKThue */
?>
<?php

$this->headscript()->appendFile($this->basePath() . '/public/' . 'myjs/Quanlysothue/Dukienthue/persistAction.js');
?>

<div class="row-fluid">
	<div class="span12">
		<!-- BEGIN NOTIFICATION PORTLET-->
		<div class="widget red">
			<div class="widget-title">
				<h4>
					<i class="icon-bar-chart"></i> Notifications
				</h4>
				<span class="tools"> <a href="javascript:;"
					class="icon-chevron-down"></a> <a href="javascript:;"
					class="icon-remove"></a>
				</span>
			</div>
			<div class="widget-body">
			<?php /* @var $kq ketqua */?>
				<?php if(isset($kq)):?>
				     <?php if($kq->getKq()==true):?>
        				        <div class="alert alert-block alert-success fade in">
					<button data-dismiss="alert" class="close" type="button">×</button>
					<h4 class="alert-heading">Success!</h4>
					<p><?php echo $kq->getMessenger();?>.</p>
				</div>
				<?php else:?>
				<div class="alert alert-block alert-error fade in">
					<button data-dismiss="alert" class="close" type="button">×</button>
					<h4 class="alert-heading">Error!</h4>
					<p><?php echo $kq->getMessenger();?>.</p>
				</div>
				     <?php endif;?>

				<?php endif;?>



			</div>
		</div>
		<!-- END NOTIFICATION PORTLET-->
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<!-- BEGIN SAMPLE FORMPORTLET-->
		<div class="widget green">
			<div class="widget-title">
				<h4>
					<i class="icon-reorder"></i> Thêm dự kiến doanh số
				</h4>
				<span class="tools"> <a href="javascript:;"
					class="icon-chevron-down"></a>
				</span>
			</div>

			<div class="widget-body span12">
				
					<!-- BEGIN FORM-->
					<form action="" method="post" class="form-horizontal">
						<div class="row-fluid">
							<div class="span6">
								<div class="control-group">
									<label class="control-label"><?php echo $this->formLabel($form->get('KyThue'));?></label>
									<div class="controls">
										<div class="input-append date" id="dpMonths"
											data-date="102/2012" data-date-format="mm-yyyy"
											data-date-viewmode="years" data-date-minviewmode="months">
								<?php echo $this->formElement($form->get('KyThue'));?>

								 <span class="add-on"> <i class="icon-calendar"> </i></span>
											<div class="progress progress-striped active"
												id="progress_kythue"
												style="width: 219.5px; margin-bottom: 0px; display: none;">
												<div style="width: 100%;" class="bar"></div>
											</div>
										</div>
										<p class="help-block"><?php echo $this->formElementErrors($form->get('KyThue'));?></p>
									</div>
								</div>

								<div class="control-group">
									<label class="control-label"> <?php echo $this->formlabel($form->get('TieuMuc'));?></label>
									<div class="controls">

										<div class="input-prepend input-append">
											<a id="DialogTieuMuc" href="#"><span class="add-on">+</span></a>
                            <?php echo $this->formelement($form->get('TieuMuc'));?>
    							         </div>


										<span class="help-inline"> </span>


										<p id="TenGoiTieuMuc" class="help-block"></p>
										
										<p class="help-block"><?php echo $this->formelementerrors($form->get('TieuMuc'));?></p>
									</div>
								</div>

								<div class="control-group">
									<label class="control-label"> <?php echo $this->formlabel($form->get('MaSoThue'));?></label>
									<div class="controls">
									
									<div class="input-prepend input-append">
											<a id="DialogMaSoThue" href="#"><span class="add-on">+</span></a>
                            <?php echo $this->formelement($form->get('MaSoThue'));?>
    							</div>
									
									
                            
					  
						  <span class="help-inline"> </span>
										<p class="help-block"><?php echo $this->formelementerrors($form->get('MaSoThue'));?></p>
									</div>
								</div>
							</div>
							<div class="span6">
								<div class="span8 bio" style="margin-top: -20px">


									<h2>
										<span id="nnt_ten">.........</span>
									</h2>
									<p>
										<label>Mã số thuế </label>: <span id="nnt_masothue"></span>
									</p>
									<p>
										<label>Địa chỉ </label>: <span id="nnt_diachi"></span>
									</p>
									<p>
										<label>Số giấy phép </label>: <span id="nnt_sogpkd"></span>
									</p>
									<p>
										<label>Nghề KD </label>: <span id="nnt_nghekd"></span>
									</p>





								</div>
							</div>
						</div>
						<div class="row-fluid">

							<div class="span6">

								<div class="control-group">
									<label class="control-label"><?php echo $this->formlabel($form->get('TenGoi'));?></label>
									<div class="controls">
										<div class="input-prepend input-append">
											<span class="add-on">&nbsp;</span>  <?php echo $this->formelement($form->get('TenGoi'));?>
    							</div>
										<p class="help-block"><?php echo $this->formelementerrors($form->get('TenGoi'));?></p>
									</div>
								</div>


								<div class="control-group">
									<label class="control-label"><?php echo $this->formlabel($form->get('SanLuong'));?></label>
									<div class="controls">
										<div class="input-prepend input-append">
											<span class="add-on">$</span>  <?php echo $this->formelement($form->get('SanLuong'));?>
    							</div>
										<p class="help-block"><?php echo $this->formelementerrors($form->get('SanLuong'));?></p>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label"><?php echo $this->formlabel($form->get('DoanhThuChiuThue'));?></label>
									<div class="controls">
										<div class="input-prepend input-append">
											<span class="add-on">$</span>  <?php echo $this->formelement($form->get('DoanhThuChiuThue'));?>
    							</div>
										<p class="help-block"><?php echo $this->formelementerrors($form->get('DoanhThuChiuThue'));?></p>
									</div>
								</div>

							</div>

							<div class="span6">

								<div class="control-group">
									<label class="control-label"><?php echo $this->formlabel($form->get('TiLeTinhThue'));?></label>
									<div class="controls">
										<div class="input-prepend input-append">
											<span class="add-on">$</span>  <?php echo $this->formelement($form->get('TiLeTinhThue'));?>
							</div>
										<p class="help-block"><?php echo $this->formelementerrors($form->get('TiLeTinhThue'));?></p>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label"><?php echo $this->formlabel($form->get('ThueSuat'));?></label>
									<div class="controls">
										<div class="input-prepend input-append">
											<span class="add-on">$</span>  <?php echo $this->formelement($form->get('ThueSuat'));?>
							</div>
										<p class="help-block"><?php echo $this->formelementerrors($form->get('ThueSuat'));?></p>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label"><?php echo $this->formlabel($form->get('SoTien'));?></label>
									<div class="controls">
										<div class="input-prepend input-append">
											<span class="add-on">$</span>  <?php echo $this->formelement($form->get('SoTien'));?>
							</div>
										<p class="help-block"><?php echo $this->formelementerrors($form->get('SoTien'));?></p>
									</div>
								</div>
						
						<?php echo $this->formelement($form->get('HanhDong'));?>
						<?php echo $this->formelementerrors($form->get('HanhDong'));?>
						 </div>

						</div>

						<div class="form-actions">
							<button style="margin-left: 100px;" type="submit"
								class="btn btn-success">Submit</button>
							<button type="button" class="btn">Clean form</button>
						</div>

					</form>
					<!-- END FORM-->
				

			</div>

		</div>
		<!-- END SAMPLE FORM PORTLET-->
	</div>
</div>

<div id="DialogTable" style="width: 800px; margin-left: -400px;"
	class="modal hide fade in" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel1" aria-hidden="false"
	style="display: block;">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"
			aria-hidden="true">×</button>
		<h3 id="myModalLabel1">...</h3>
	</div>
	<div class="modal-body">
		<p>Body goes here...</p>
	</div>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
		<button class="btn btn-primary" id="DialogTable_btnOK">OK</button>
	</div>
</div>